/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesHistoryJsonQueryResponse, GetMatchesHistoryJsonQueryParams, GetMatchesHistoryJson400, GetMatchesHistoryJson401, GetMatchesHistoryJson404, GetMatchesHistoryJson500 } from "../../types/GetMatchesHistoryJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesHistoryJsonUrl() {
  const res = { method: 'GET', url: `/matches/history.json` as const }  
  return res
}

/**
 * @description Возвращает матчи за дату или диапазон дат.
 * @summary История матчей (завершённые)
 * {@link /matches/history.json}
 */
export async function getMatchesHistoryJson(params?: GetMatchesHistoryJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesHistoryJsonQueryResponse, ResponseErrorConfig<GetMatchesHistoryJson400 | GetMatchesHistoryJson401 | GetMatchesHistoryJson404 | GetMatchesHistoryJson500>, unknown>({ method : "GET", url : getGetMatchesHistoryJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}