/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesLiveJsonQueryResponse, GetMatchesLiveJsonQueryParams, GetMatchesLiveJson400, GetMatchesLiveJson401, GetMatchesLiveJson404, GetMatchesLiveJson500 } from "../../types/GetMatchesLiveJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesLiveJsonUrl() {
  const res = { method: 'GET', url: `/matches/live.json` as const }  
  return res
}

/**
 * @description Возвращает список текущих live-матчей и недавно завершённых.
 * @summary Live-матчи (текущие и недавно завершённые)
 * {@link /matches/live.json}
 */
export async function getMatchesLiveJson(params?: GetMatchesLiveJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesLiveJsonQueryResponse, ResponseErrorConfig<GetMatchesLiveJson400 | GetMatchesLiveJson401 | GetMatchesLiveJson404 | GetMatchesLiveJson500>, unknown>({ method : "GET", url : getGetMatchesLiveJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}