/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesLiveJsonQueryResponse, GetMatchesLiveJsonQueryParams, GetMatchesLiveJson400, GetMatchesLiveJson401, GetMatchesLiveJson404, GetMatchesLiveJson500 } from "../../types/GetMatchesLiveJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesLiveJsonUrl() {
  const res = { method: 'GET', url: `/matches/live.json` as const }  
  return res
}

/**
 * @description Возвращает список футбольных матчей, которые **идут в данный момент** (лайвскор). Матчи появляются за ~15 минут до начала (со статусом `NOT STARTED`) и остаются в фиде примерно до 1-3 часов после окончания (со статусом `FINISHED`).  Поддерживается фильтрация по стране, соревнованию или команде, а также выбор конкретного матча по `fixture_id`. Без фильтров возвращаются все текущие лайв-матчи.  **Параметры фильтрации:**  - `competition_id` – ID или список ID соревнований (через запятую) для ограничение выборки матчей определённых турниров.  - `country_id` – ID страны для вывода матчей, проходящих только в этой стране.  - `team_id` – ID команды для вывода только матчей с участием этой команды.  - `fixture_id` – ID запланированного матча для получения его лайв-статуса (если матч уже начался).  - `lang` – код языка для перевода названий команд, турниров и пр. (опционально).  **Пример запроса без фильтров:**  `GET /matches/live.json?key=YOUR_KEY&secret=YOUR_SECRET`  **Пример запроса (лайв-матчи серии A Италии):**  `GET /matches/live.json?competition_id=4&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Live-матчи (текущие в игре)
 * {@link /matches/live.json}
 */
export async function getMatchesLiveJson(params?: GetMatchesLiveJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesLiveJsonQueryResponse, ResponseErrorConfig<GetMatchesLiveJson400 | GetMatchesLiveJson401 | GetMatchesLiveJson404 | GetMatchesLiveJson500>, unknown>({ method : "GET", url : getGetMatchesLiveJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}