/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetTeamsMatchesJsonQueryResponse, GetTeamsMatchesJsonQueryParams, GetTeamsMatchesJson400, GetTeamsMatchesJson401, GetTeamsMatchesJson404, GetTeamsMatchesJson500 } from "../../types/GetTeamsMatchesJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetTeamsMatchesJsonUrl() {
  const res = { method: 'GET', url: `/teams/matches.json` as const }  
  return res
}

/**
 * @description Возвращает несколько последних матчей (завершённых или live) указанной команды. Например, можно получить последние N результатов команды для отображения её текущей формы.  **Параметры:** `team_id` – ID команды, `number` – сколько последних матчей вернуть (например, 5 или 10).  **Пример запроса (последние 7 матчей команды с ID=46):**  `GET /teams/matches.json?team_id=46&number=7&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Последние матчи команды
 * {@link /teams/matches.json}
 */
export async function getTeamsMatchesJson(params?: GetTeamsMatchesJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetTeamsMatchesJsonQueryResponse, ResponseErrorConfig<GetTeamsMatchesJson400 | GetTeamsMatchesJson401 | GetTeamsMatchesJson404 | GetTeamsMatchesJson500>, unknown>({ method : "GET", url : getGetTeamsMatchesJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}