/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetTeamsHead2HeadJsonQueryResponse, GetTeamsHead2HeadJsonQueryParams, GetTeamsHead2HeadJson400, GetTeamsHead2HeadJson401, GetTeamsHead2HeadJson404, GetTeamsHead2HeadJson500 } from "../../types/GetTeamsHead2HeadJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetTeamsHead2HeadJsonUrl() {
  const res = { method: 'GET', url: `/teams/head2head.json` as const }  
  return res
}

/**
 * @description Предоставляет сравнительную статистику двух команд на основе их последних встреч друг с другом и, возможно, последних игр вообще. Позволяет оценить форму команд перед их очным матчем.  **Параметры:** необходимо указать `team1_id` и `team2_id` – ID двух команд для сравнения.  **Пример запроса:**  `GET /teams/head2head.json?team1_id=6581&team2_id=202&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Сравнение двух команд (H2H)
 * {@link /teams/head2head.json}
 */
export async function getTeamsHead2HeadJson(params: GetTeamsHead2HeadJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetTeamsHead2HeadJsonQueryResponse, ResponseErrorConfig<GetTeamsHead2HeadJson400 | GetTeamsHead2HeadJson401 | GetTeamsHead2HeadJson404 | GetTeamsHead2HeadJson500>, unknown>({ method : "GET", url : getGetTeamsHead2HeadJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}