/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getMatchesHistoryJson } from "./getMatchesHistoryJson.ts";
import { getMatchesLiveJson } from "./getMatchesLiveJson.ts";

export function matchesService() {
  return { getMatchesLiveJson, getMatchesHistoryJson }
}