/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getMatchesHistoryJson } from "./getMatchesHistoryJson.ts";
import { getMatchesLiveJson } from "./getMatchesLiveJson.ts";
import { getTeamsHead2HeadJson } from "./getTeamsHead2HeadJson.ts";
import { getTeamsMatchesJson } from "./getTeamsMatchesJson.ts";

export function matchesService() {
  return { getMatchesLiveJson, getMatchesHistoryJson, getTeamsHead2HeadJson, getTeamsMatchesJson }
}