/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getFixturesMatchesJson } from './getFixturesMatchesJson.ts'

export function fixturesService() {
  return { getFixturesMatchesJson }
}
