/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetFixturesMatchesJsonQueryResponse,
  GetFixturesMatchesJsonQueryParams,
  GetFixturesMatchesJson400,
  GetFixturesMatchesJson401,
  GetFixturesMatchesJson404,
  GetFixturesMatchesJson500,
} from '../../types/GetFixturesMatchesJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetFixturesMatchesJsonUrl() {
  const res = { method: 'GET', url: `/fixtures/matches.json` as const }
  return res
}

/**
 * @description Возвращает список **будущих запланированных матчей** (fixtures). По умолчанию возвращаются матчи на ближайшие даты; желательно указывать параметры фильтрации по дате или турниру для управления объёмом данных.  **Особенности:**  - В ответе возвращается не более 30 матчей на страницу (`page`), если матчей больше – будет указана `next_page` ссылка для следующей страницы.  - Поле `id` в объекте fixture – постоянный идентификатор запланированного матча. После начала матча ему будет соответствовать другой `match_id` (live/история), но связь сохраняе��ся через поле `fixture_id` в live/history данных.  - Можно фильтровать по `date` (конкретный день, или специальное значение `today` для сегодняшних матчей), по диапазону `from`-`to`, по `competition_id` (матчи конкретного турнира), по `team_id` (матчи конкретной команды), по `country_id` (матчи в указанной стране).  **Пример запроса (все матчи на сегодня):**  `GET /fixtures/matches.json?date=today&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Запланированные матчи (расписание)
 * {@link /fixtures/matches.json}
 */
export async function getFixturesMatchesJson(
  params?: GetFixturesMatchesJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetFixturesMatchesJsonQueryResponse,
    ResponseErrorConfig<
      | GetFixturesMatchesJson400
      | GetFixturesMatchesJson401
      | GetFixturesMatchesJson404
      | GetFixturesMatchesJson500
    >,
    unknown
  >({ method: 'GET', url: getGetFixturesMatchesJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
