/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetFixturesMatchesJsonQueryResponse,
  GetFixturesMatchesJsonQueryParams,
  GetFixturesMatchesJson400,
  GetFixturesMatchesJson401,
  GetFixturesMatchesJson404,
  GetFixturesMatchesJson500,
} from '../../types/GetFixturesMatchesJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetFixturesMatchesJsonUrl() {
  const res = { method: 'GET', url: `/fixtures/matches.json` as const }
  return res
}

/**
 * @description Возвращает будущие игры (fixtures) по дате/диапазону, турнирам, странам, командам.
 * @summary Предстоящие матчи (расписание)
 * {@link /fixtures/matches.json}
 */
export async function getFixturesMatchesJson(
  params?: GetFixturesMatchesJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetFixturesMatchesJsonQueryResponse,
    ResponseErrorConfig<
      | GetFixturesMatchesJson400
      | GetFixturesMatchesJson401
      | GetFixturesMatchesJson404
      | GetFixturesMatchesJson500
    >,
    unknown
  >({ method: 'GET', url: getGetFixturesMatchesJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
