/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTranslationsCompetitionsJsonQueryResponse,
  GetTranslationsCompetitionsJsonQueryParams,
} from '../../types/GetTranslationsCompetitionsJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTranslationsCompetitionsJsonUrl() {
  const res = { method: 'GET', url: `/translations/competitions.json` as const }
  return res
}

/**
 * @summary Переводы соревнований
 * {@link /translations/competitions.json}
 */
export async function getTranslationsCompetitionsJson(
  params?: GetTranslationsCompetitionsJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTranslationsCompetitionsJsonQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetTranslationsCompetitionsJsonUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res
}
