/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetTranslationsTeamsJsonQueryResponse, GetTranslationsTeamsJsonQueryParams, GetTranslationsTeamsJson400, GetTranslationsTeamsJson401 } from "../../types/GetTranslationsTeamsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetTranslationsTeamsJsonUrl() {
  const res = { method: 'GET', url: `/translations/teams.json` as const }  
  return res
}

/**
 * @summary Переводы команд
 * {@link /translations/teams.json}
 */
export async function getTranslationsTeamsJson(params?: GetTranslationsTeamsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetTranslationsTeamsJsonQueryResponse, ResponseErrorConfig<GetTranslationsTeamsJson400 | GetTranslationsTeamsJson401>, unknown>({ method : "GET", url : getGetTranslationsTeamsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}