/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTranslationsCountriesJsonQueryResponse,
  GetTranslationsCountriesJsonQueryParams,
} from '../../types/GetTranslationsCountriesJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTranslationsCountriesJsonUrl() {
  const res = { method: 'GET', url: `/translations/countries.json` as const }
  return res
}

/**
 * @summary Переводы стран
 * {@link /translations/countries.json}
 */
export async function getTranslationsCountriesJson(
  params?: GetTranslationsCountriesJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTranslationsCountriesJsonQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetTranslationsCountriesJsonUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res
}
