/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTranslationsFederationsJsonQueryResponse,
  GetTranslationsFederationsJsonQueryParams,
} from '../../types/GetTranslationsFederationsJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTranslationsFederationsJsonUrl() {
  const res = { method: 'GET', url: `/translations/federations.json` as const }
  return res
}

/**
 * @summary Переводы федераций
 * {@link /translations/federations.json}
 */
export async function getTranslationsFederationsJson(
  params?: GetTranslationsFederationsJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTranslationsFederationsJsonQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetTranslationsFederationsJsonUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res
}
