/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getTranslationsCompetitionsJson } from "./getTranslationsCompetitionsJson.ts";
import { getTranslationsCountriesJson } from "./getTranslationsCountriesJson.ts";
import { getTranslationsFederationsJson } from "./getTranslationsFederationsJson.ts";
import { getTranslationsTeamsJson } from "./getTranslationsTeamsJson.ts";

export function translationsService() {
  return { getTranslationsTeamsJson, getTranslationsCompetitionsJson, getTranslationsCountriesJson, getTranslationsFederationsJson }
}