/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ApiError = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}
