/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Competition } from "./Competition.ts";
import type { Pagination } from "./Pagination.ts";

export type CompetitionsResponse = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @description Массив соревнований (в API называется \'competition\', не \'competitions\')
         * @type array | undefined
        */
        competition?: Competition[] | undefined;
        /**
         * @type object | undefined
        */
        pagination?: Pagination | undefined;
    } | undefined;
};