/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Country } from "./Country.ts";
import type { Federation } from "./Federation.ts";
import type { SeasonRef } from "./SeasonRef.ts";

export type Competition = {
    /**
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @type string | undefined
    */
    name?: string | undefined;
    /**
     * @type boolean
    */
    is_league?: (boolean | null) | undefined;
    /**
     * @type boolean
    */
    is_cup?: (boolean | null) | undefined;
    /**
     * @type boolean
    */
    has_groups?: (boolean | null) | undefined;
    /**
     * @type boolean
    */
    active?: (boolean | null) | undefined;
    /**
     * @type boolean
    */
    national_teams_only?: (boolean | null) | undefined;
    /**
     * @type object | undefined
    */
    country?: Country | undefined;
    /**
     * @type array | undefined
    */
    federations?: Federation[] | undefined;
    /**
     * @type object | undefined
    */
    season?: SeasonRef | undefined;
};