/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Country } from "./Country.ts";
import type { Federation } from "./Federation.ts";
import type { SeasonRef } from "./SeasonRef.ts";

export type Competition = {
    /**
     * @description ID соревнования (строка в API)
     * @type string | undefined
    */
    id?: string | undefined;
    /**
     * @type string | undefined
    */
    name?: string | undefined;
    /**
     * @description Строка \'1\' или \'0\'
     * @type string
    */
    is_league?: (string | null) | undefined;
    /**
     * @description Строка \'1\' или \'0\'
     * @type string
    */
    is_cup?: (string | null) | undefined;
    /**
     * @description Уровень лиги
     * @type string
    */
    tier?: (string | null) | undefined;
    /**
     * @description Строка \'1\' или \'0\'
     * @type string
    */
    has_groups?: (string | null) | undefined;
    /**
     * @description Строка \'1\' или \'0\'
     * @type string
    */
    active?: (string | null) | undefined;
    /**
     * @description Строка \'1\' или \'0\'
     * @type string
    */
    national_teams_only?: (string | null) | undefined;
    /**
     * @description Массив стран (в отличие от единичного объекта country)
     * @type array | undefined
    */
    countries?: Country[] | undefined;
    /**
     * @type array | undefined
    */
    federations?: Federation[] | undefined;
    /**
     * @type object | undefined
    */
    season?: SeasonRef | undefined;
};