/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Country } from './Country.ts'
import type { Federation } from './Federation.ts'

export type Competition = {
  /**
   * @description Уникальный ID соревнования (лиги или кубка)
   * @type integer | undefined
   */
  id?: number | undefined
  /**
   * @description Название соревнования
   * @type string | undefined
   */
  name?: string | undefined
  /**
   * @description Признак лиги (true, если это лиговый турнир, false для кубка)
   * @type boolean | undefined
   */
  is_league?: boolean | undefined
  /**
   * @description Признак кубкового турнира (обратен is_league: true для кубков, false для лиг)
   * @type boolean | undefined
   */
  is_cup?: boolean | undefined
  /**
   * @description Уровень (дивизион) соревнования. Например, 1 – высший дивизион страны, 2 – второй и т.д. Международные турниры могут иметь tier = 0.
   * @type integer | undefined
   */
  tier?: number | undefined
  /**
   * @description Имеет ли турнир групповой этап (true, если соревнование разбито на группы)
   * @type boolean | undefined
   */
  has_groups?: boolean | undefined
  /**
   * @description Активно ли соревнование (true – поддерживается в текущем сезоне; false – данные есть лишь в архиве)
   * @type boolean | undefined
   */
  active?: boolean | undefined
  /**
   * @description Флаг, обозначающий, что в турнире участвуют только национальные сборные (true для турниров сборных, false для клубных)
   * @type boolean | undefined
   */
  national_teams_only?: boolean | undefined
  /**
   * @description Список стран, к которым относится соревнование (может быть пустым для международных турниров)
   * @type array | undefined
   */
  countries?: Country[] | undefined
  /**
   * @description Список федераций, к которым относится соревнование (например, UEFA для Лиги Чемпионов; может быть пустым для национальных лиг)
   * @type array | undefined
   */
  federations?: Federation[] | undefined
  /**
   * @description Текущий сезон соревнования (последний на момент запроса). Содержит идентификатор и временные рамки сезона.
   * @type object
   */
  season?:
    | ({
        /**
         * @description ID сезона
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @description Название сезона (например, \"2021/2022\" или \"2023\")
         * @type string | undefined
         */
        name?: string | undefined
        /**
         * @description Дата начала сезона (календарная)
         * @type string | undefined, date
         */
        start?: Date | undefined
        /**
         * @description Дата окончания сезона
         * @type string | undefined, date
         */
        end?: Date | undefined
      } | null)
    | undefined
}
