/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Строка турнирной таблицы из реального API /competitions/standings.json
 */
export type CompetitionsStandingsTableRow = {
  /**
   * @description ID лиги
   * @type string | undefined
   */
  league_id?: string | undefined
  /**
   * @description ID сезона
   * @type string | undefined
   */
  season_id?: string | undefined
  /**
   * @description Название команды
   * @type string | undefined
   */
  name?: string | undefined
  /**
   * @description Позиция в таблице
   * @type string | undefined
   */
  rank?: string | undefined
  /**
   * @description Очки
   * @type string | undefined
   */
  points?: string | undefined
  /**
   * @description Количество матчей
   * @type string | undefined
   */
  matches?: string | undefined
  /**
   * @description Разность мячей
   * @type string | undefined
   */
  goal_diff?: string | undefined
  /**
   * @description Забитые голы
   * @type string | undefined
   */
  goals_scored?: string | undefined
  /**
   * @description Пропущенные голы
   * @type string | undefined
   */
  goals_conceded?: string | undefined
  /**
   * @description Поражения
   * @type string | undefined
   */
  lost?: string | undefined
  /**
   * @description Ничьи
   * @type string | undefined
   */
  drawn?: string | undefined
  /**
   * @description Победы
   * @type string | undefined
   */
  won?: string | undefined
  /**
   * @description ID команды
   * @type string | undefined
   */
  team_id?: string | undefined
  /**
   * @description ID соревнования
   * @type string | undefined
   */
  competition_id?: string | undefined
  /**
   * @description ID группы
   * @type string | undefined
   */
  group_id?: string | undefined
  /**
   * @description Название группы
   * @type string | undefined
   */
  group_name?: string | undefined
  /**
   * @description Название стадии
   * @type string | undefined
   */
  stage_name?: string | undefined
  /**
   * @description ID стадии
   * @type string | undefined
   */
  stage_id?: string | undefined
  /**
   * @description Форма команды (последние результаты): W - победа, D - ничья, L - поражение
   * @type string
   */
  form?: (string | null) | undefined
}
