/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Country = {
    /**
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @type string | undefined
    */
    name?: string | undefined;
    /**
     * @description ISO/FIFA код страны (если доступно)
     * @type string
    */
    code?: (string | null) | undefined;
    /**
     * @description Реальная (true) или условная/регион (false)
     * @type boolean | undefined
    */
    is_real?: boolean | undefined;
    /**
     * @description Имя файла PNG флага или URL (в зависимости от реализации)
     * @type string
    */
    flag?: (string | null) | undefined;
};