/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Country } from './Country.ts'
import type { Pagination } from './Pagination.ts'

export type CountriesResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type array | undefined
         */
        countries?: Country[] | undefined
        /**
         * @type object | undefined
         */
        pagination?: Pagination | undefined
      }
    | undefined
}
