/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Country = {
  /**
   * @description Уникальный ID страны
   * @type integer | undefined
   */
  id?: number | undefined
  /**
   * @description Название страны
   * @type string | undefined
   */
  name?: string | undefined
  /**
   * @description Флаг реальной страны (true, если страна реально существует, false – например, для условных объединений вроде «World» или континентов)
   * @type boolean | undefined
   */
  is_real?: boolean | undefined
  /**
   * @description Код FIFA (если есть)
   * @type string
   */
  fifa_code?: (string | null) | undefined
  /**
   * @description Код UEFA (если есть)
   * @type string
   */
  uefa_code?: (string | null) | undefined
  /**
   * @description Название файла флага страны (PNG) на CDN. Например, `AUS.png`. Для получения самого изображения используется отдельный эндпоинт флагов.
   * @type string
   */
  flag?: (string | null) | undefined
  /**
   * @description Объект федерации, к которой относится страна (если применимо; для реальных стран указывается соответствующая конфедерация, например UEFA). Содержит поля `id` и `name` федерации.
   * @type object
   */
  federation?:
    | ({
        /**
         * @description ID федерации
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @description Название федерации
         * @type string | undefined
         */
        name?: string | undefined
      } | null)
    | undefined
  /**
   * @description Объект национальной сборной этой страны (если информация доступна и страна реальная). Содержит сведения о национальной команде.
   * @type object
   */
  national_team?:
    | ({
        /**
         * @description ID команды (национальной сборной)
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @description Название национальной команды
         * @type string | undefined
         */
        name?: string | undefined
        /**
         * @description Название домашнего стадиона сборной (если есть данные)
         * @type string | undefined
         */
        stadium?: string | undefined
        /**
         * @description Локация (город/стадион) национальной команды (если есть данные)
         * @type string | undefined
         */
        location?: string | undefined
      } | null)
    | undefined
}
