/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Event } from './Event.ts'
import type { Match } from './Match.ts'

export type EventsResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @description Универсальная модель матча (live/история)
         * @type object | undefined
         */
        match?: Match | undefined
        /**
         * @type array | undefined
         */
        events?: Event[] | undefined
      }
    | undefined
}
