/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Event = {
    /**
     * @type integer
    */
    time?: (number | null) | undefined;
    /**
     * @type integer
    */
    added_time?: (number | null) | undefined;
    /**
     * @type string | undefined
    */
    type?: string | undefined;
    /**
     * @type boolean | undefined
    */
    is_home?: boolean | undefined;
    /**
     * @type boolean | undefined
    */
    is_away?: boolean | undefined;
    /**
     * @type string
    */
    player?: (string | null) | undefined;
    /**
     * @type integer
    */
    player_id?: (number | null) | undefined;
    /**
     * @type string
    */
    assist?: (string | null) | undefined;
    /**
     * @type integer
    */
    assist_id?: (number | null) | undefined;
    /**
     * @description Например, Penalty, Missed Penalty
     * @type string
    */
    detail?: (string | null) | undefined;
    /**
     * @description Счет после события
     * @type string
    */
    result?: (string | null) | undefined;
    /**
     * @type integer | undefined
    */
    sort?: number | undefined;
    /**
     * @type string | undefined
    */
    label?: string | undefined;
};