/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Событие матча (гол, карточка, замена и т.д.)
*/
export type Event = {
    /**
     * @description Уникальный ID события
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @description Минута матча, когда произошло событие
     * @type integer | undefined
    */
    time?: number | undefined;
    /**
     * @description Тип события (кодовое обозначение)
     * @type string | undefined
    */
    event?: string | undefined;
    /**
     * @description Человекочитаемое название события (на английском или на языке `lang`, если запрошен перевод)
     * @type string | undefined
    */
    label?: string | undefined;
    /**
     * @description Признак события, относящегося к домашней команде (true, если событие связано с home-командой)
     * @type boolean | undefined
    */
    is_home?: boolean | undefined;
    /**
     * @description Признак события, относящегося к гостевой команде (true для away-команды)
     * @type boolean | undefined
    */
    is_away?: boolean | undefined;
    /**
     * @description Основной игрок, связанный с событием (например, автор гола или получивший карточку)
     * @type object
    */
    player?: ({
        /**
         * @description ID игрока
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @description Имя игрока
         * @type string | undefined
        */
        name?: string | undefined;
    } | null) | undefined;
    /**
     * @description Дополнительный игрок, связанный с событием (например, ассистент гола или заменённый игрок)
     * @type object
    */
    info?: ({
        /**
         * @description ID второго игрока
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @description Имя второго игрока
         * @type string | undefined
        */
        name?: string | undefined;
    } | null) | undefined;
    /**
     * @description Порядковый номер события в хронологии матча (начиная с 0; если два события в одну минуту, используется sort д��я упорядочения)
     * @type integer | undefined
    */
    sort?: number | undefined;
};