/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Federation = {
  /**
   * @description ID футбольной федерации (конфедерации), например 1 для FIFA
   * @type integer | undefined
   */
  id?: number | undefined
  /**
   * @description Название федерации
   * @type string | undefined
   */
  name?: string | undefined
}
