/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Federation = {
    /**
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @type string | undefined
    */
    name?: string | undefined;
};