/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Federation } from './Federation.ts'

export type FederationsResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type array | undefined
         */
        federations?: Federation[] | undefined
      }
    | undefined
}
