/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Competition } from "./Competition.ts";
import type { Odds } from "./Odds.ts";
import type { Team } from "./Team.ts";

export type Fixture = {
    /**
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @type object | undefined
    */
    competition?: Competition | undefined;
    /**
     * @type string | undefined, date
    */
    date?: Date | undefined;
    /**
     * @type string | undefined
    */
    time?: string | undefined;
    /**
     * @type string
    */
    location?: (string | null) | undefined;
    /**
     * @type string
    */
    round?: (string | null) | undefined;
    /**
     * @type integer
    */
    group_id?: (number | null) | undefined;
    /**
     * @type object | undefined
    */
    home?: Team | undefined;
    /**
     * @type object | undefined
    */
    away?: Team | undefined;
    /**
     * @type object | undefined
    */
    odds?: Odds | undefined;
};