/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { Country } from './Country.ts'
import type { Federation } from './Federation.ts'
import type { Team } from './Team.ts'

/**
 * @description Модель запланированного матча (fixture)
 */
export type Fixture = {
  /**
   * @description ID запланированного матча (постоянный идентификатор, отличающийся от будущего match_id)
   * @type integer | undefined
   */
  id?: number | undefined
  /**
   * @description Дата, на которую назначен матч
   * @type string | undefined, date
   */
  date?: Date | undefined
  /**
   * @description Время начала матча (UTC)
   * @type string | undefined
   */
  time?: string | undefined
  /**
   * @type object | undefined
   */
  home?: Team | undefined
  /**
   * @type object | undefined
   */
  away?: Team | undefined
  /**
   * @type object | undefined
   */
  competition?: Competition | undefined
  /**
   * @type object | undefined
   */
  country?: Country | undefined
  /**
   * @type object | undefined
   */
  federation?: Federation | undefined
  /**
   * @description Место проведения (стадион или город) запланированного матча
   * @type string
   */
  location?: (string | null) | undefined
  /**
   * @description Тур или стадия, в рамках которых запланирован матч. Может быть числом (номер тура) или кодом стадии (например, QF, SF для четверть-/полуфинала)
   * @type string | undefined
   */
  round?: string | undefined
  /**
   * @description ID группы, в которой состоится матч (для турниров с группами). 0 или null, если матч не привязан к группе
   * @type integer
   */
  group_id?: (number | null) | undefined
  /**
   * @description Объект коэффициентов ставок, аналогичный полю `odds` в модели матча. Для запланированных матчей, как правило, заполнены только прематчевые коэффициенты, live-коэффициенты будут null до начала игры.
   * @type object | undefined
   */
  odds?:
    | {
        /**
         * @type object | undefined
         */
        pre?:
          | {
              /**
               * @type number | undefined
               */
              '1'?: number | undefined
              /**
               * @type number | undefined
               */
              '2'?: number | undefined
              /**
               * @type number | undefined
               */
              X?: number | undefined
            }
          | undefined
        /**
         * @type object | undefined
         */
        live?:
          | {
              /**
               * @type number
               */
              '1'?: (number | null) | undefined
              /**
               * @type number
               */
              '2'?: (number | null) | undefined
              /**
               * @type number
               */
              X?: (number | null) | undefined
            }
          | undefined
      }
    | undefined
}
