/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Fixture } from './Fixture.ts'

export type FixturesResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type array | undefined
         */
        fixtures?: Fixture[] | undefined
        /**
         * @type string
         */
        next_page?: (string | null) | undefined
        /**
         * @type string
         */
        prev_page?: (string | null) | undefined
      }
    | undefined
}
