/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { VerifyResponse } from './VerifyResponse.ts'

/**
 * @description Ключ действителен
 */
export type GetAuthVerifyJson200 = VerifyResponse

/**
 * @description Некорректный запрос
 */
export type GetAuthVerifyJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetAuthVerifyJson401 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetAuthVerifyJson500 = ApiError

export type GetAuthVerifyJsonQueryResponse = GetAuthVerifyJson200

export type GetAuthVerifyJsonQuery = {
  Response: GetAuthVerifyJson200
  Errors: GetAuthVerifyJson400 | GetAuthVerifyJson401 | GetAuthVerifyJson500
}
