/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Запрос выполнен – ключ и секрет валидны (возвращается подтверждающее сообщение)
 */
export type GetAuthVerifyJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type string | undefined
         */
        message?: string | undefined
      }
    | undefined
}

/**
 * @description Ошибка запроса
 */
export type GetAuthVerifyJson400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Неверный ключ API или секрет (не авторизовано)
 */
export type GetAuthVerifyJson401 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Эндпоинт не найден
 */
export type GetAuthVerifyJson404 = unknown

/**
 * @description Внутренняя ошибка сервера
 */
export type GetAuthVerifyJson500 = unknown

export type GetAuthVerifyJsonQueryResponse = GetAuthVerifyJson200

export type GetAuthVerifyJsonQuery = {
  Response: GetAuthVerifyJson200
  Errors: GetAuthVerifyJson400 | GetAuthVerifyJson401 | GetAuthVerifyJson404 | GetAuthVerifyJson500
}
