/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetCountriesFlagPngQueryParams = {
    /**
     * @description ID страны для фильтрации результатов (например, получать данные только по соревнованиям или матчам в заданной стране)
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID команды для фильтрации результатов (например, получать только матчи с участием указанной команды)
     * @type integer | undefined
    */
    team_id?: number | undefined;
};

/**
 * @description OK – возвращено изображение флага (PNG)
*/
export type GetCountriesFlagPng200 = Blob;

/**
 * @description Ошибка запроса
*/
export type GetCountriesFlagPng400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetCountriesFlagPng401 = unknown;

/**
 * @description Флаг для данной страны/команды не найден
*/
export type GetCountriesFlagPng404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetCountriesFlagPng500 = unknown;

export type GetCountriesFlagPngQueryResponse = GetCountriesFlagPng200;

export type GetCountriesFlagPngQuery = {
    Response: GetCountriesFlagPng200;
    QueryParams: GetCountriesFlagPngQueryParams;
    Errors: GetCountriesFlagPng400 | GetCountriesFlagPng401 | GetCountriesFlagPng404 | GetCountriesFlagPng500;
};