/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { TopScorerEntry } from './TopScorerEntry.ts'

export type GetCompetitionsTopscorersJsonQueryParams = {
  /**
   * @description ID соревнования (или несколько ID через запятую) для фильтрации результатов
   * @type string | undefined
   */
  competition_id?: string | undefined
  /**
   * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
   * @type string | undefined
   */
  lang?: string | undefined
}

/**
 * @description OK – список лучших бомбардиров получен
 */
export type GetCompetitionsTopscorersJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type object | undefined
         */
        competition?: Competition | undefined
        /**
         * @description Объект выпуска соревнования (текущая «редакция» турнира, может включать id выпуска и is_current)
         * @type object | undefined
         */
        edition?:
          | {
              /**
               * @type integer | undefined
               */
              id?: number | undefined
              /**
               * @type integer | undefined
               */
              season_id?: number | undefined
              /**
               * @type boolean | undefined
               */
              is_current?: boolean | undefined
            }
          | undefined
        /**
         * @description Объект сезона соревнования
         * @type object | undefined
         */
        season?:
          | {
              /**
               * @type integer | undefined
               */
              id?: number | undefined
              /**
               * @type string | undefined
               */
              name?: string | undefined
              /**
               * @type string | undefined, date
               */
              start?: Date | undefined
              /**
               * @type string | undefined, date
               */
              end?: Date | undefined
            }
          | undefined
        /**
         * @description Список топ-бомбардиров
         * @type array | undefined
         */
        topscorers?: TopScorerEntry[] | undefined
      }
    | undefined
}

/**
 * @description Ошибка запроса
 */
export type GetCompetitionsTopscorersJson400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Неавторизован (неверные ключ или секрет)
 */
export type GetCompetitionsTopscorersJson401 = unknown

/**
 * @description Соревнование не найдено
 */
export type GetCompetitionsTopscorersJson404 = unknown

/**
 * @description Внутренняя ошибка сервера
 */
export type GetCompetitionsTopscorersJson500 = unknown

export type GetCompetitionsTopscorersJsonQueryResponse = GetCompetitionsTopscorersJson200

export type GetCompetitionsTopscorersJsonQuery = {
  Response: GetCompetitionsTopscorersJson200
  QueryParams: GetCompetitionsTopscorersJsonQueryParams
  Errors:
    | GetCompetitionsTopscorersJson400
    | GetCompetitionsTopscorersJson401
    | GetCompetitionsTopscorersJson404
    | GetCompetitionsTopscorersJson500
}
