/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { CountriesResponse } from "./CountriesResponse.ts";

export type GetCountriesListJsonQueryParams = {
    /**
     * @description Номер страницы (по умолчанию 1)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description Размер страницы (по умолчанию 30, максимум 100)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    size?: number | undefined;
};

/**
 * @description Страны
*/
export type GetCountriesListJson200 = CountriesResponse;

/**
 * @description Некорректный запрос
*/
export type GetCountriesListJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetCountriesListJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetCountriesListJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetCountriesListJson500 = ApiError;

export type GetCountriesListJsonQueryResponse = GetCountriesListJson200;

export type GetCountriesListJsonQuery = {
    Response: GetCountriesListJson200;
    QueryParams: GetCountriesListJsonQueryParams;
    Errors: GetCountriesListJson400 | GetCountriesListJson401 | GetCountriesListJson404 | GetCountriesListJson500;
};