/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { TopCardEntry } from './TopCardEntry.ts'

export type GetCompetitionsTopcardsJsonQueryParams = {
  /**
   * @description ID соревнования (или несколько ID через запятую) для фильтрации результатов
   * @type string | undefined
   */
  competition_id?: string | undefined
  /**
   * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
   * @type string | undefined
   */
  lang?: string | undefined
}

/**
 * @description OK – дисциплинарный список получен
 */
export type GetCompetitionsTopcardsJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type object | undefined
         */
        competition?: Competition | undefined
        /**
         * @type object | undefined
         */
        edition?:
          | {
              /**
               * @type integer | undefined
               */
              id?: number | undefined
              /**
               * @type integer | undefined
               */
              season_id?: number | undefined
              /**
               * @type boolean | undefined
               */
              is_current?: boolean | undefined
            }
          | undefined
        /**
         * @type object | undefined
         */
        season?:
          | {
              /**
               * @type integer | undefined
               */
              id?: number | undefined
              /**
               * @type string | undefined
               */
              name?: string | undefined
              /**
               * @type string | undefined, date
               */
              start?: Date | undefined
              /**
               * @type string | undefined, date
               */
              end?: Date | undefined
            }
          | undefined
        /**
         * @description Список игроков и их карточки
         * @type array | undefined
         */
        topcards?: TopCardEntry[] | undefined
      }
    | undefined
}

/**
 * @description Ошибка запроса
 */
export type GetCompetitionsTopcardsJson400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Неавторизован (неверные ключ или секрет)
 */
export type GetCompetitionsTopcardsJson401 = unknown

/**
 * @description Соревнование не найдено или не поддерживается данным методом
 */
export type GetCompetitionsTopcardsJson404 = unknown

/**
 * @description Внутренняя ошибка сервера
 */
export type GetCompetitionsTopcardsJson500 = unknown

export type GetCompetitionsTopcardsJsonQueryResponse = GetCompetitionsTopcardsJson200

export type GetCompetitionsTopcardsJsonQuery = {
  Response: GetCompetitionsTopcardsJson200
  QueryParams: GetCompetitionsTopcardsJsonQueryParams
  Errors:
    | GetCompetitionsTopcardsJson400
    | GetCompetitionsTopcardsJson401
    | GetCompetitionsTopcardsJson404
    | GetCompetitionsTopcardsJson500
}
