/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";

export type GetCountriesFlagJsonQueryParams = {
    /**
     * @description ID национальной команды
     * @type integer
    */
    team_id: number;
};

/**
 * @description PNG-файл флага
*/
export type GetCountriesFlagJson200 = Blob;

/**
 * @description Некорректный запрос
*/
export type GetCountriesFlagJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetCountriesFlagJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetCountriesFlagJson404 = ApiError;

export type GetCountriesFlagJsonQueryResponse = GetCountriesFlagJson200;

export type GetCountriesFlagJsonQuery = {
    Response: GetCountriesFlagJson200;
    QueryParams: GetCountriesFlagJsonQueryParams;
    Errors: GetCountriesFlagJson400 | GetCountriesFlagJson401 | GetCountriesFlagJson404;
};