/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { TopScorersResponse } from "./TopScorersResponse.ts";

export type GetCompetitionsTopscorersJsonQueryParams = {
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description ID соревнования
     * @type integer
    */
    competition_id: number;
};

/**
 * @description Топ бомбардиров
*/
export type GetCompetitionsTopscorersJson200 = TopScorersResponse;

/**
 * @description Некорректный запрос
*/
export type GetCompetitionsTopscorersJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetCompetitionsTopscorersJson401 = ApiError;

/**
 * @description Соревнование не найдено
*/
export type GetCompetitionsTopscorersJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetCompetitionsTopscorersJson500 = ApiError;

export type GetCompetitionsTopscorersJsonQueryResponse = GetCompetitionsTopscorersJson200;

export type GetCompetitionsTopscorersJsonQuery = {
    Response: GetCompetitionsTopscorersJson200;
    QueryParams: GetCompetitionsTopscorersJsonQueryParams;
    Errors: GetCompetitionsTopscorersJson400 | GetCompetitionsTopscorersJson401 | GetCompetitionsTopscorersJson404 | GetCompetitionsTopscorersJson500;
};