/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { CompetitionsResponse } from "./CompetitionsResponse.ts";

export type GetCompetitionsListJsonQueryParams = {
    /**
     * @description Номер страницы (по умолчанию 1)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description Размер страницы (по умолчанию 30, максимум 100)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    size?: number | undefined;
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description ID страны
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID федерации
     * @type integer | undefined
    */
    federation_id?: number | undefined;
};

/**
 * @description Соревнования
*/
export type GetCompetitionsListJson200 = CompetitionsResponse;

/**
 * @description Некорректный запрос
*/
export type GetCompetitionsListJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetCompetitionsListJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetCompetitionsListJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetCompetitionsListJson500 = ApiError;

export type GetCompetitionsListJsonQueryResponse = GetCompetitionsListJson200;

export type GetCompetitionsListJsonQuery = {
    Response: GetCompetitionsListJson200;
    QueryParams: GetCompetitionsListJsonQueryParams;
    Errors: GetCompetitionsListJson400 | GetCompetitionsListJson401 | GetCompetitionsListJson404 | GetCompetitionsListJson500;
};