/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Competition } from "./Competition.ts";

export type GetCompetitionsListJsonQueryParams = {
    /**
     * @description Номер страницы для постраничной навигации (при наличии более 30 элементов в ответе)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description Количество элементов на страницу (если поддерживается эндпоинтом; по умолчанию 30)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    size?: number | undefined;
    /**
     * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description ID страны для фильтрации результатов (например, получать данные только по соревнованиям или матчам в заданной стране)
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID футбольной федерации для фильтрации списка стран или соревнований (например, 1 для FIFA)
     * @type integer | undefined
    */
    federation_id?: number | undefined;
};

/**
 * @description OK – список соревнований получен
*/
export type GetCompetitionsListJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @description Список соревнований
         * @type array | undefined
        */
        competition?: Competition[] | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetCompetitionsListJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetCompetitionsListJson401 = unknown;

/**
 * @description Эндпоинт не найден
*/
export type GetCompetitionsListJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetCompetitionsListJson500 = unknown;

export type GetCompetitionsListJsonQueryResponse = GetCompetitionsListJson200;

export type GetCompetitionsListJsonQuery = {
    Response: GetCompetitionsListJson200;
    QueryParams: GetCompetitionsListJsonQueryParams;
    Errors: GetCompetitionsListJson400 | GetCompetitionsListJson401 | GetCompetitionsListJson404 | GetCompetitionsListJson500;
};