/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Country } from "./Country.ts";

export type GetCountriesListJsonQueryParams = {
    /**
     * @description Номер страницы для постраничной навигации (при наличии более 30 элементов в ответе)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description Количество элементов на страницу (если поддерживается эндпоинтом; по умолчанию 30)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    size?: number | undefined;
    /**
     * @description ID футбольной федерации для фильтрации списка стран или соревнований (например, 1 для FIFA)
     * @type integer | undefined
    */
    federation_id?: number | undefined;
};

/**
 * @description OK – список стран получен
*/
export type GetCountriesListJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @description Список стран
         * @type array | undefined
        */
        country?: Country[] | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetCountriesListJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetCountriesListJson401 = unknown;

/**
 * @description Эндпоинт не найден
*/
export type GetCountriesListJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetCountriesListJson500 = unknown;

export type GetCountriesListJsonQueryResponse = GetCountriesListJson200;

export type GetCountriesListJsonQuery = {
    Response: GetCountriesListJson200;
    QueryParams: GetCountriesListJsonQueryParams;
    Errors: GetCountriesListJson400 | GetCountriesListJson401 | GetCountriesListJson404 | GetCountriesListJson500;
};