/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { FederationsResponse } from './FederationsResponse.ts'

/**
 * @description Федераций
 */
export type GetFederationsListJson200 = FederationsResponse

/**
 * @description Некорректный запрос
 */
export type GetFederationsListJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetFederationsListJson401 = ApiError

/**
 * @description Не найдено
 */
export type GetFederationsListJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetFederationsListJson500 = ApiError

export type GetFederationsListJsonQueryResponse = GetFederationsListJson200

export type GetFederationsListJsonQuery = {
  Response: GetFederationsListJson200
  Errors:
    | GetFederationsListJson400
    | GetFederationsListJson401
    | GetFederationsListJson404
    | GetFederationsListJson500
}
