/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description OK – список федераций получен
*/
export type GetFederationsListJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type boolean | undefined
        */
        success?: boolean | undefined;
        /**
         * @type object | undefined
        */
        data?: {
            /**
             * @description Список федераций
             * @type array | undefined
            */
            federation?: {
                /**
                 * @description ID федерации (может быть строкой)
                 * @type string | undefined
                */
                id?: string | undefined;
                /**
                 * @description Название федерации
                 * @type string | undefined
                */
                name?: string | undefined;
            }[] | undefined;
        } | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetFederationsListJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetFederationsListJson401 = unknown;

/**
 * @description Эндпоинт не найден
*/
export type GetFederationsListJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetFederationsListJson500 = unknown;

export type GetFederationsListJsonQueryResponse = GetFederationsListJson200;

export type GetFederationsListJsonQuery = {
    Response: GetFederationsListJson200;
    Errors: GetFederationsListJson400 | GetFederationsListJson401 | GetFederationsListJson404 | GetFederationsListJson500;
};