/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { FixturesResponse } from "./FixturesResponse.ts";

export type GetFixturesMatchesJsonQueryParams = {
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description Номер страницы (по умолчанию 1)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description Размер страницы (по умолчанию 30, максимум 100)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    size?: number | undefined;
    /**
     * @description ID соревнования (или несколько через запятую)
    */
    competition_id?: (number | string) | undefined;
    /**
     * @description ID страны
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID команды
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @description Начальная дата диапазона (YYYY-MM-DD)
     * @type string | undefined, date
    */
    from?: Date | undefined;
    /**
     * @description Конечная дата диапазона (YYYY-MM-DD)
     * @type string | undefined, date
    */
    to?: Date | undefined;
    /**
     * @description Конкретная дата (YYYY-MM-DD)
     * @type string | undefined, date
    */
    date?: Date | undefined;
};

/**
 * @description Список фикстур
*/
export type GetFixturesMatchesJson200 = FixturesResponse;

/**
 * @description Некорректный запрос
*/
export type GetFixturesMatchesJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetFixturesMatchesJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetFixturesMatchesJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetFixturesMatchesJson500 = ApiError;

export type GetFixturesMatchesJsonQueryResponse = GetFixturesMatchesJson200;

export type GetFixturesMatchesJsonQuery = {
    Response: GetFixturesMatchesJson200;
    QueryParams: GetFixturesMatchesJsonQueryParams;
    Errors: GetFixturesMatchesJson400 | GetFixturesMatchesJson401 | GetFixturesMatchesJson404 | GetFixturesMatchesJson500;
};