/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { LiveMatchesResponse } from "./LiveMatchesResponse.ts";

export type GetMatchesLiveJsonQueryParams = {
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description Номер страницы (по умолчанию 1)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description ID соревнования (или несколько через запятую)
    */
    competition_id?: (number | string) | undefined;
    /**
     * @description ID страны
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID команды
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @description ID фикстуры (запланированного матча)
     * @type integer | undefined
    */
    fixture_id?: number | undefined;
};

/**
 * @description Список live-матчей
*/
export type GetMatchesLiveJson200 = LiveMatchesResponse;

/**
 * @description Некорректный запрос
*/
export type GetMatchesLiveJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetMatchesLiveJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetMatchesLiveJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetMatchesLiveJson500 = ApiError;

export type GetMatchesLiveJsonQueryResponse = GetMatchesLiveJson200;

export type GetMatchesLiveJsonQuery = {
    Response: GetMatchesLiveJson200;
    QueryParams: GetMatchesLiveJsonQueryParams;
    Errors: GetMatchesLiveJson400 | GetMatchesLiveJson401 | GetMatchesLiveJson404 | GetMatchesLiveJson500;
};