/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Match } from "./Match.ts";

export type GetMatchesLiveJsonQueryParams = {
    /**
     * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description Номер страницы для постраничной навигации (при наличии более 30 элементов в ответе)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description ID соревнования (или несколько ID через запятую) для фильтрации результатов
     * @type string | undefined
    */
    competition_id?: string | undefined;
    /**
     * @description ID страны для фильтрации результатов (например, получать данные только по соревнованиям или матчам в заданной стране)
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID команды для фильтрации результатов (например, получать только матчи с участием указанной команды)
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @description ID запланированного матча (fixture). Можно указать, чтобы получить конкретный live-матч по соответствующему fixture_id. В истории также поле `fixture_id` связывает матч с запланированным ранее событием.
     * @type integer | undefined
    */
    fixture_id?: number | undefined;
};

/**
 * @description OK – список текущих матчей получен
*/
export type GetMatchesLiveJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @description Список объектов матчей (все поля матча, включая команды, счёт и т.п.)
         * @type array | undefined
        */
        match?: Match[] | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetMatchesLiveJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetMatchesLiveJson401 = unknown;

/**
 * @description Эндпоинт не найден
*/
export type GetMatchesLiveJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetMatchesLiveJson500 = unknown;

export type GetMatchesLiveJsonQueryResponse = GetMatchesLiveJson200;

export type GetMatchesLiveJsonQuery = {
    Response: GetMatchesLiveJson200;
    QueryParams: GetMatchesLiveJsonQueryParams;
    Errors: GetMatchesLiveJson400 | GetMatchesLiveJson401 | GetMatchesLiveJson404 | GetMatchesLiveJson500;
};