/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { LineupsResponse } from "./LineupsResponse.ts";

export type GetMatchesLineupsJsonQueryParams = {
    /**
     * @description ID матча (live/история)
     * @type integer
    */
    match_id: number;
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
};

/**
 * @description Составы
*/
export type GetMatchesLineupsJson200 = LineupsResponse;

/**
 * @description Некорректный запрос
*/
export type GetMatchesLineupsJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetMatchesLineupsJson401 = ApiError;

/**
 * @description Матч не найден
*/
export type GetMatchesLineupsJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetMatchesLineupsJson500 = ApiError;

export type GetMatchesLineupsJsonQueryResponse = GetMatchesLineupsJson200;

export type GetMatchesLineupsJsonQuery = {
    Response: GetMatchesLineupsJson200;
    QueryParams: GetMatchesLineupsJsonQueryParams;
    Errors: GetMatchesLineupsJson400 | GetMatchesLineupsJson401 | GetMatchesLineupsJson404 | GetMatchesLineupsJson500;
};