/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { EventsResponse } from "./EventsResponse.ts";

export type GetMatchesEventsJsonQueryParams = {
    /**
     * @description ID матча для событий
     * @type integer
    */
    id: number;
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
};

/**
 * @description События матча
*/
export type GetMatchesEventsJson200 = EventsResponse;

/**
 * @description Некорректный запрос
*/
export type GetMatchesEventsJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetMatchesEventsJson401 = ApiError;

/**
 * @description Матч не найден
*/
export type GetMatchesEventsJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetMatchesEventsJson500 = ApiError;

export type GetMatchesEventsJsonQueryResponse = GetMatchesEventsJson200;

export type GetMatchesEventsJsonQuery = {
    Response: GetMatchesEventsJson200;
    QueryParams: GetMatchesEventsJsonQueryParams;
    Errors: GetMatchesEventsJson400 | GetMatchesEventsJson401 | GetMatchesEventsJson404 | GetMatchesEventsJson500;
};