/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { StatsResponse } from './StatsResponse.ts'

export type GetMatchesStatsJsonQueryParams = {
  /**
   * @description ID матча (live/история)
   * @type integer
   */
  match_id: number
}

/**
 * @description Статистика матча (home/away)
 */
export type GetMatchesStatsJson200 = StatsResponse

/**
 * @description Некорректный запрос
 */
export type GetMatchesStatsJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetMatchesStatsJson401 = ApiError

/**
 * @description Матч не найден
 */
export type GetMatchesStatsJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetMatchesStatsJson500 = ApiError

export type GetMatchesStatsJsonQueryResponse = GetMatchesStatsJson200

export type GetMatchesStatsJsonQuery = {
  Response: GetMatchesStatsJson200
  QueryParams: GetMatchesStatsJsonQueryParams
  Errors:
    | GetMatchesStatsJson400
    | GetMatchesStatsJson401
    | GetMatchesStatsJson404
    | GetMatchesStatsJson500
}
