/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { HistoryMatchesResponse } from './HistoryMatchesResponse.ts'

export type GetMatchesHistoryJsonQueryParams = {
  /**
   * @description ISO 639-1 код языка для перевода (например, `ru`)
   * @type string | undefined
   */
  lang?: string | undefined
  /**
   * @description Номер страницы (по умолчанию 1)
   * @minLength 1
   * @type integer | undefined
   */
  page?: number | undefined
  /**
   * @description ID соревнования (или несколько через запятую)
   */
  competition_id?: (number | string) | undefined
  /**
   * @description ID страны
   * @type integer | undefined
   */
  country_id?: number | undefined
  /**
   * @description ID команды
   * @type integer | undefined
   */
  team_id?: number | undefined
  /**
   * @description Начальная дата диапазона (YYYY-MM-DD)
   * @type string | undefined, date
   */
  from?: Date | undefined
  /**
   * @description Конечная дата диапазона (YYYY-MM-DD)
   * @type string | undefined, date
   */
  to?: Date | undefined
  /**
   * @description Конкретная дата (YYYY-MM-DD)
   * @type string | undefined, date
   */
  date?: Date | undefined
}

/**
 * @description Список завершённых матчей
 */
export type GetMatchesHistoryJson200 = HistoryMatchesResponse

/**
 * @description Некорректный запрос
 */
export type GetMatchesHistoryJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetMatchesHistoryJson401 = ApiError

/**
 * @description Не найдено
 */
export type GetMatchesHistoryJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetMatchesHistoryJson500 = ApiError

export type GetMatchesHistoryJsonQueryResponse = GetMatchesHistoryJson200

export type GetMatchesHistoryJsonQuery = {
  Response: GetMatchesHistoryJson200
  QueryParams: GetMatchesHistoryJsonQueryParams
  Errors:
    | GetMatchesHistoryJson400
    | GetMatchesHistoryJson401
    | GetMatchesHistoryJson404
    | GetMatchesHistoryJson500
}
