/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MatchStats } from "./MatchStats.ts";

export type GetMatchesStatsJsonQueryParams = {
    /**
     * @description ID матча. Используется в эндпоинтах статистики и составов для указания конкретного матча (live или завершённого).
     * @type integer
    */
    match_id: number;
};

/**
 * @description OK – статистика матча получена
*/
export type GetMatchesStatsJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @description Статистика матча: к��ючи объекта – наименования статистических показателей, значения – строки вида `\"Дома:Гости\"` (либо `null`, если данные недоступны).
     * @type object | undefined
    */
    data?: MatchStats | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetMatchesStatsJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetMatchesStatsJson401 = unknown;

/**
 * @description Матч не найден или статистика недоступна
*/
export type GetMatchesStatsJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetMatchesStatsJson500 = unknown;

export type GetMatchesStatsJsonQueryResponse = GetMatchesStatsJson200;

export type GetMatchesStatsJsonQuery = {
    Response: GetMatchesStatsJson200;
    QueryParams: GetMatchesStatsJsonQueryParams;
    Errors: GetMatchesStatsJson400 | GetMatchesStatsJson401 | GetMatchesStatsJson404 | GetMatchesStatsJson500;
};