/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Match } from './Match.ts'

export type GetMatchesHistoryJsonQueryParams = {
  /**
   * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
   * @type string | undefined
   */
  lang?: string | undefined
  /**
   * @description Номер страницы для постраничной навигации (при наличии более 30 элементов в ответе)
   * @minLength 1
   * @type integer | undefined
   */
  page?: number | undefined
  /**
   * @description ID соревнования (или несколько ID через запятую) для фильтрации результатов
   * @type string | undefined
   */
  competition_id?: string | undefined
  /**
   * @description ID страны для фильтрации результатов (например, получать данные только по соревнованиям или матчам в заданной стране)
   * @type integer | undefined
   */
  country_id?: number | undefined
  /**
   * @description ID команды для фильтрации результатов (например, получать только матчи с участием указанной команды)
   * @type integer | undefined
   */
  team_id?: number | undefined
  /**
   * @description Конкретная дата для фильтрации (формат YYYY-MM-DD) – возвращает данные (матчи) за указанную дату. Специальное значение `today` означает текущий день.
   * @type string | undefined, date
   */
  date?: Date | undefined
  /**
   * @description Начало диапазона дат для фильтрации истории/расписания матчей. Используется вместе с параметром `to`.
   * @type string | undefined, date
   */
  from?: Date | undefined
  /**
   * @description Конец диапазона дат для фильтрации истории/расписания матчей (включительно). Если не указан при использовании `from`, считается равным `from`.
   * @type string | undefined, date
   */
  to?: Date | undefined
}

/**
 * @description OK – список завершённых матчей получен
 */
export type GetMatchesHistoryJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @description Список матчей (завершённых) с подробной информацией
         * @type array | undefined
         */
        match?: Match[] | undefined
        /**
         * @description URL для следующей с��раницы результатов (если есть следующая страница)
         * @type string
         */
        next_page?: (string | null) | undefined
        /**
         * @description URL для предыдущей страницы результатов (если есть)
         * @type string
         */
        prev_page?: (string | null) | undefined
      }
    | undefined
}

/**
 * @description Ошибка запроса
 */
export type GetMatchesHistoryJson400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Неавторизован (неверные ключ или секрет)
 */
export type GetMatchesHistoryJson401 = unknown

/**
 * @description Эндпоинт не найден
 */
export type GetMatchesHistoryJson404 = unknown

/**
 * @description Внутренняя ошибка сервера
 */
export type GetMatchesHistoryJson500 = unknown

export type GetMatchesHistoryJsonQueryResponse = GetMatchesHistoryJson200

export type GetMatchesHistoryJsonQuery = {
  Response: GetMatchesHistoryJson200
  QueryParams: GetMatchesHistoryJsonQueryParams
  Errors:
    | GetMatchesHistoryJson400
    | GetMatchesHistoryJson401
    | GetMatchesHistoryJson404
    | GetMatchesHistoryJson500
}
