/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Lineup } from "./Lineup.ts";

export type GetMatchesLineupsJsonQueryParams = {
    /**
     * @description ID матча. Используется в эндпоинтах статистики и составов для указания конкретного матча (live или завершённого).
     * @type integer
    */
    match_id: number;
    /**
     * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
     * @type string | undefined
    */
    lang?: string | undefined;
};

/**
 * @description OK – составы получены
*/
export type GetMatchesLineupsJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type integer | undefined
        */
        match_id?: number | undefined;
        /**
         * @description Состав команды на матч (стартовый состав и запасные)
         * @type object | undefined
        */
        home?: Lineup | undefined;
        /**
         * @description Состав команды на матч (стартовый состав и запасные)
         * @type object | undefined
        */
        away?: Lineup | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetMatchesLineupsJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetMatchesLineupsJson401 = unknown;

/**
 * @description Матч не найден или составы недоступны
*/
export type GetMatchesLineupsJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetMatchesLineupsJson500 = unknown;

export type GetMatchesLineupsJsonQueryResponse = GetMatchesLineupsJson200;

export type GetMatchesLineupsJsonQuery = {
    Response: GetMatchesLineupsJson200;
    QueryParams: GetMatchesLineupsJsonQueryParams;
    Errors: GetMatchesLineupsJson400 | GetMatchesLineupsJson401 | GetMatchesLineupsJson404 | GetMatchesLineupsJson500;
};