/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { OddsResponse } from './OddsResponse.ts'

export type GetOddsLiveJsonQueryParams = {
  /**
   * @description ID соревнования (или несколько через запятую)
   */
  competition_id?: (number | string) | undefined
}

/**
 * @description Коэффициенты во время матча
 */
export type GetOddsLiveJson200 = OddsResponse

/**
 * @description Некорректный запрос
 */
export type GetOddsLiveJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetOddsLiveJson401 = ApiError

/**
 * @description Не найдено
 */
export type GetOddsLiveJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetOddsLiveJson500 = ApiError

export type GetOddsLiveJsonQueryResponse = GetOddsLiveJson200

export type GetOddsLiveJsonQuery = {
  Response: GetOddsLiveJson200
  QueryParams: GetOddsLiveJsonQueryParams
  Errors: GetOddsLiveJson400 | GetOddsLiveJson401 | GetOddsLiveJson404 | GetOddsLiveJson500
}
