/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { OddsResponse } from "./OddsResponse.ts";

export type GetOddsPreJsonQueryParams = {
    /**
     * @description ID соревнования (или несколько через запятую)
    */
    competition_id?: (number | string) | undefined;
    /**
     * @description Конкретная дата (YYYY-MM-DD)
     * @type string | undefined, date
    */
    date?: Date | undefined;
};

/**
 * @description Коэффициенты до матча
*/
export type GetOddsPreJson200 = OddsResponse;

/**
 * @description Некорректный запрос
*/
export type GetOddsPreJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetOddsPreJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetOddsPreJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetOddsPreJson500 = ApiError;

export type GetOddsPreJsonQueryResponse = GetOddsPreJson200;

export type GetOddsPreJsonQuery = {
    Response: GetOddsPreJson200;
    QueryParams: GetOddsPreJsonQueryParams;
    Errors: GetOddsPreJson400 | GetOddsPreJson401 | GetOddsPreJson404 | GetOddsPreJson500;
};