/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { SeasonsResponse } from "./SeasonsResponse.ts";

/**
 * @description Сезоны
*/
export type GetSeasonsListJson200 = SeasonsResponse;

/**
 * @description Некорректный запрос
*/
export type GetSeasonsListJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetSeasonsListJson401 = ApiError;

/**
 * @description Не найдено
*/
export type GetSeasonsListJson404 = ApiError;

/**
 * @description Внутренняя ошибка
*/
export type GetSeasonsListJson500 = ApiError;

export type GetSeasonsListJsonQueryResponse = GetSeasonsListJson200;

export type GetSeasonsListJsonQuery = {
    Response: GetSeasonsListJson200;
    Errors: GetSeasonsListJson400 | GetSeasonsListJson401 | GetSeasonsListJson404 | GetSeasonsListJson500;
};