/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Competition } from "./Competition.ts";
import type { Country } from "./Country.ts";
import type { Event } from "./Event.ts";
import type { Federation } from "./Federation.ts";
import type { Team } from "./Team.ts";

export type GetScoresEventsJsonQueryParams = {
    /**
     * @description ID матча, для которого запрашиваются события (поле `id` из live или history данных)
     * @type integer
    */
    id: number;
    /**
     * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
     * @type string | undefined
    */
    lang?: string | undefined;
};

/**
 * @description OK – события матча получены
*/
export type GetScoresEventsJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @description Общая информация о матче (идентификатор, дата, счёт и т.п.)
         * @type object | undefined
        */
        match?: {
            /**
             * @type integer | undefined
            */
            id?: number | undefined;
            /**
             * @type string | undefined
            */
            date?: string | undefined;
            /**
             * @description Статус времени матча (например, AP – после пенальти)
             * @type string | undefined
            */
            time?: string | undefined;
            /**
             * @type string | undefined
            */
            status?: string | undefined;
            /**
             * @type string | undefined
            */
            added?: string | undefined;
            /**
             * @type string | undefined
            */
            last_changed?: string | undefined;
            /**
             * @type string | undefined
            */
            location?: string | undefined;
            /**
             * @type string | undefined
            */
            fixture_id?: string | undefined;
            /**
             * @type string | undefined
            */
            scheduled?: string | undefined;
            /**
             * @type object | undefined
            */
            odds?: {
                /**
                 * @type object | undefined
                */
                pre?: object | undefined;
                /**
                 * @type object | undefined
                */
                live?: object | undefined;
            } | undefined;
            /**
             * @type object | undefined
            */
            outcomes?: {
                /**
                 * @type string | undefined
                */
                half_time?: string | undefined;
                /**
                 * @type string | undefined
                */
                full_time?: string | undefined;
                /**
                 * @type string | undefined
                */
                extra_time?: string | undefined;
                /**
                 * @type string | undefined
                */
                penalty_shootout?: string | undefined;
            } | undefined;
            /**
             * @type object | undefined
            */
            scores?: {
                /**
                 * @type string | undefined
                */
                score?: string | undefined;
                /**
                 * @type string | undefined
                */
                ht_score?: string | undefined;
                /**
                 * @type string | undefined
                */
                ft_score?: string | undefined;
                /**
                 * @type string | undefined
                */
                et_score?: string | undefined;
                /**
                 * @type string | undefined
                */
                ps_score?: string | undefined;
            } | undefined;
            /**
             * @type object | undefined
            */
            home?: Team | undefined;
            /**
             * @type object | undefined
            */
            away?: Team | undefined;
            /**
             * @type object | undefined
            */
            competition?: Competition | undefined;
            /**
             * @type object | undefined
            */
            country?: Country | undefined;
            /**
             * @type object | undefined
            */
            federation?: Federation | undefined;
        } | undefined;
        /**
         * @description Список событий матча (каждый элемент – объект события с типом, игроками и проч.)
         * @type array | undefined
        */
        event?: Event[] | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetScoresEventsJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetScoresEventsJson401 = unknown;

/**
 * @description Эндпоинт или матч не найден
*/
export type GetScoresEventsJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetScoresEventsJson500 = unknown;

export type GetScoresEventsJsonQueryResponse = GetScoresEventsJson200;

export type GetScoresEventsJsonQuery = {
    Response: GetScoresEventsJson200;
    QueryParams: GetScoresEventsJsonQueryParams;
    Errors: GetScoresEventsJson400 | GetScoresEventsJson401 | GetScoresEventsJson404 | GetScoresEventsJson500;
};