/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK – список сезонов получен
 */
export type GetSeasonsListJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @description Список сезонов
         * @type array | undefined
         */
        season?:
          | {
              /**
               * @type integer | undefined
               */
              id?: number | undefined
              /**
               * @type string | undefined
               */
              name?: string | undefined
              /**
               * @type string | undefined, date
               */
              start?: Date | undefined
              /**
               * @type string | undefined, date
               */
              end?: Date | undefined
            }[]
          | undefined
      }
    | undefined
}

/**
 * @description Ошибка запроса
 */
export type GetSeasonsListJson400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Неавторизован (неверные ключ или секрет)
 */
export type GetSeasonsListJson401 = unknown

/**
 * @description Эндпоинт не найден
 */
export type GetSeasonsListJson404 = unknown

/**
 * @description Внутренняя ошибка сервера
 */
export type GetSeasonsListJson500 = unknown

export type GetSeasonsListJsonQueryResponse = GetSeasonsListJson200

export type GetSeasonsListJsonQuery = {
  Response: GetSeasonsListJson200
  Errors:
    | GetSeasonsListJson400
    | GetSeasonsListJson401
    | GetSeasonsListJson404
    | GetSeasonsListJson500
}
