/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { TableRow } from './TableRow.ts'

export const getTablesStandingsJsonQueryParamsIncludeFormEnum = {
  '0': 0,
  '1': 1,
} as const

export type GetTablesStandingsJsonQueryParamsIncludeFormEnum =
  (typeof getTablesStandingsJsonQueryParamsIncludeFormEnum)[keyof typeof getTablesStandingsJsonQueryParamsIncludeFormEnum]

export type GetTablesStandingsJsonQueryParams = {
  /**
   * @description ID соревнования (или несколько ID через запятую) для фильтрации результатов
   * @type string | undefined
   */
  competition_id?: string | undefined
  /**
   * @description ID сезона, для которого нужна таблица (если не текущий)
   * @type integer | undefined
   */
  season?: number | undefined
  /**
   * @description Имя группы, если нужно standings конкретной группы (для много-групповых соревнований, напр. \"A\")
   * @type string | undefined
   */
  group?: string | undefined
  /**
   * @description ID группы, если известен и нужен standings конкретной группы
   * @type integer | undefined
   */
  group_id?: number | undefined
  /**
   * @description Если =1, в ответ включается форма команд за последние 5-6 матчей (последовательность W/D/L)
   * @type integer | undefined
   */
  include_form?: GetTablesStandingsJsonQueryParamsIncludeFormEnum | undefined
  /**
   * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
   * @type string | undefined
   */
  lang?: string | undefined
}

/**
 * @description OK – таблица получена
 */
export type GetTablesStandingsJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type object | undefined
         */
        competition?: Competition | undefined
        /**
         * @description Таблица позиций команд
         * @type array | undefined
         */
        table?: TableRow[] | undefined
      }
    | undefined
}

/**
 * @description Ошибка запроса
 */
export type GetTablesStandingsJson400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type string | undefined
   */
  error?: string | undefined
}

/**
 * @description Неавторизован (неверные ключ или секрет)
 */
export type GetTablesStandingsJson401 = unknown

/**
 * @description Соревнование не найдено
 */
export type GetTablesStandingsJson404 = unknown

/**
 * @description Внутренняя ошибка сервера
 */
export type GetTablesStandingsJson500 = unknown

export type GetTablesStandingsJsonQueryResponse = GetTablesStandingsJson200

export type GetTablesStandingsJsonQuery = {
  Response: GetTablesStandingsJson200
  QueryParams: GetTablesStandingsJsonQueryParams
  Errors:
    | GetTablesStandingsJson400
    | GetTablesStandingsJson401
    | GetTablesStandingsJson404
    | GetTablesStandingsJson500
}
