/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { TeamsResponse } from './TeamsResponse.ts'

export type GetTeamsListJsonQueryParams = {
  /**
   * @description Номер страницы (по умолчанию 1)
   * @minLength 1
   * @type integer | undefined
   */
  page?: number | undefined
  /**
   * @description Размер страницы (по умолчанию 30, максимум 100)
   * @minLength 1
   * @maxLength 100
   * @type integer | undefined
   */
  size?: number | undefined
  /**
   * @description ISO 639-1 код языка для перевода (например, `ru`)
   * @type string | undefined
   */
  lang?: string | undefined
  /**
   * @description ID страны
   * @type integer | undefined
   */
  country_id?: number | undefined
  /**
   * @description ID федерации
   * @type integer | undefined
   */
  federation_id?: number | undefined
}

/**
 * @description Команды
 */
export type GetTeamsListJson200 = TeamsResponse

/**
 * @description Некорректный запрос
 */
export type GetTeamsListJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetTeamsListJson401 = ApiError

/**
 * @description Не найдено
 */
export type GetTeamsListJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetTeamsListJson500 = ApiError

export type GetTeamsListJsonQueryResponse = GetTeamsListJson200

export type GetTeamsListJsonQuery = {
  Response: GetTeamsListJson200
  QueryParams: GetTeamsListJsonQueryParams
  Errors: GetTeamsListJson400 | GetTeamsListJson401 | GetTeamsListJson404 | GetTeamsListJson500
}
