/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { LastMatchesResponse } from './LastMatchesResponse.ts'

export type GetTeamsLastmatchesJsonQueryParams = {
  /**
   * @description ID команды
   * @type integer | undefined
   */
  team_id?: number | undefined
  /**
   * @description Кол-во последних матчей команды (1..30)
   * @minLength 1
   * @maxLength 30
   * @type integer
   */
  number: number
}

/**
 * @description Последние матчи
 */
export type GetTeamsLastmatchesJson200 = LastMatchesResponse

/**
 * @description Некорректный запрос
 */
export type GetTeamsLastmatchesJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetTeamsLastmatchesJson401 = ApiError

/**
 * @description Команда не найдена
 */
export type GetTeamsLastmatchesJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetTeamsLastmatchesJson500 = ApiError

export type GetTeamsLastmatchesJsonQueryResponse = GetTeamsLastmatchesJson200

export type GetTeamsLastmatchesJsonQuery = {
  Response: GetTeamsLastmatchesJson200
  QueryParams: GetTeamsLastmatchesJsonQueryParams
  Errors:
    | GetTeamsLastmatchesJson400
    | GetTeamsLastmatchesJson401
    | GetTeamsLastmatchesJson404
    | GetTeamsLastmatchesJson500
}
