/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TranslationsResponse } from './TranslationsResponse.ts'

export type GetTranslationsCompetitionsJsonQueryParams = {
  /**
   * @description ISO 639-1 код языка для перевода (например, `ru`)
   * @type string | undefined
   */
  lang?: string | undefined
  /**
   * @description ID страны
   * @type integer | undefined
   */
  country_id?: number | undefined
  /**
   * @description ID федерации
   * @type integer | undefined
   */
  federation_id?: number | undefined
}

/**
 * @description Переводы (соревнования)
 */
export type GetTranslationsCompetitionsJson200 = TranslationsResponse

export type GetTranslationsCompetitionsJsonQueryResponse = GetTranslationsCompetitionsJson200

export type GetTranslationsCompetitionsJsonQuery = {
  Response: GetTranslationsCompetitionsJson200
  QueryParams: GetTranslationsCompetitionsJsonQueryParams
  Errors: any
}
