/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Team } from "./Team.ts";

export type GetTeamsListJsonQueryParams = {
    /**
     * @description Номер страницы для постраничной навигации (при наличии более 30 элементов в ответе)
     * @minLength 1
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @description Количество элементов на страницу (если поддерживается эндпоинтом; по умолчанию 30)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    size?: number | undefined;
    /**
     * @description ISO 639-1 код языка для локализации данных (например, `ru` для русского)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description ID страны для фильтрации результатов (например, получать данные только по соревнованиям или матчам в заданной стране)
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID футбольной федерации для фильтрации списка стран или соревнований (например, 1 для FIFA)
     * @type integer | undefined
    */
    federation_id?: number | undefined;
};

/**
 * @description OK – список команд получен
*/
export type GetTeamsListJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @description Список команд
         * @type array | undefined
        */
        team?: Team[] | undefined;
        /**
         * @type object | undefined
        */
        pagination?: {
            /**
             * @type integer | undefined
            */
            page?: number | undefined;
            /**
             * @type integer | undefined
            */
            size?: number | undefined;
            /**
             * @type integer | undefined
            */
            total_pages?: number | undefined;
            /**
             * @type integer | undefined
            */
            total_items?: number | undefined;
        } | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetTeamsListJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetTeamsListJson401 = unknown;

/**
 * @description Эндпоинт не найден
*/
export type GetTeamsListJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetTeamsListJson500 = unknown;

export type GetTeamsListJsonQueryResponse = GetTeamsListJson200;

export type GetTeamsListJsonQuery = {
    Response: GetTeamsListJson200;
    QueryParams: GetTeamsListJsonQueryParams;
    Errors: GetTeamsListJson400 | GetTeamsListJson401 | GetTeamsListJson404 | GetTeamsListJson500;
};