/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TranslationsResponse } from "./TranslationsResponse.ts";

export type GetTranslationsCountriesJsonQueryParams = {
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
};

/**
 * @description Переводы (страны)
*/
export type GetTranslationsCountriesJson200 = TranslationsResponse;

export type GetTranslationsCountriesJsonQueryResponse = GetTranslationsCountriesJson200;

export type GetTranslationsCountriesJsonQuery = {
    Response: GetTranslationsCountriesJson200;
    QueryParams: GetTranslationsCountriesJsonQueryParams;
    Errors: any;
};