/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TranslationsResponse } from './TranslationsResponse.ts'

export type GetTranslationsFederationsJsonQueryParams = {
  /**
   * @description ISO 639-1 код языка для перевода (например, `ru`)
   * @type string | undefined
   */
  lang?: string | undefined
}

/**
 * @description Переводы (федерации)
 */
export type GetTranslationsFederationsJson200 = TranslationsResponse

export type GetTranslationsFederationsJsonQueryResponse = GetTranslationsFederationsJson200

export type GetTranslationsFederationsJsonQuery = {
  Response: GetTranslationsFederationsJson200
  QueryParams: GetTranslationsFederationsJsonQueryParams
  Errors: any
}
