/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiError } from './ApiError.ts'
import type { Match } from './Match.ts'

export type GetTeamsHead2HeadJsonQueryParams = {
  /**
   * @description ID первой команды
   * @type integer
   */
  team1_id: number
  /**
   * @description ID второй команды
   * @type integer
   */
  team2_id: number
}

/**
 * @description Последние матчи команд и между собой
 */
export type GetTeamsHead2HeadJson200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type array | undefined
         */
        team1_last6?: Match[] | undefined
        /**
         * @type array | undefined
         */
        team2_last6?: Match[] | undefined
        /**
         * @type array | undefined
         */
        h2h_last6?: Match[] | undefined
      }
    | undefined
}

/**
 * @description Некорректный запрос
 */
export type GetTeamsHead2HeadJson400 = ApiError

/**
 * @description Неавторизовано
 */
export type GetTeamsHead2HeadJson401 = ApiError

/**
 * @description Одна из команд не найдена
 */
export type GetTeamsHead2HeadJson404 = ApiError

/**
 * @description Внутренняя ошибка
 */
export type GetTeamsHead2HeadJson500 = ApiError

export type GetTeamsHead2HeadJsonQueryResponse = GetTeamsHead2HeadJson200

export type GetTeamsHead2HeadJsonQuery = {
  Response: GetTeamsHead2HeadJson200
  QueryParams: GetTeamsHead2HeadJsonQueryParams
  Errors:
    | GetTeamsHead2HeadJson400
    | GetTeamsHead2HeadJson401
    | GetTeamsHead2HeadJson404
    | GetTeamsHead2HeadJson500
}
