/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Match } from "./Match.ts";
import type { Team } from "./Team.ts";

export type GetTeamsMatchesJsonQueryParams = {
    /**
     * @description ID команды для фильтрации результатов (например, получать только матчи с участием указанной команды)
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @description Количество последних матчей команды, которое нужно получить (для эндпоинта последних матчей команды)
     * @type integer | undefined
    */
    number?: number | undefined;
};

/**
 * @description OK – последние матчи команды получены
*/
export type GetTeamsMatchesJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type object | undefined
        */
        team?: Team | undefined;
        /**
         * @description Список последних матчей команды
         * @type array | undefined
        */
        last_matches?: Match[] | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetTeamsMatchesJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetTeamsMatchesJson401 = unknown;

/**
 * @description Команда не найдена
*/
export type GetTeamsMatchesJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetTeamsMatchesJson500 = unknown;

export type GetTeamsMatchesJsonQueryResponse = GetTeamsMatchesJson200;

export type GetTeamsMatchesJsonQuery = {
    Response: GetTeamsMatchesJson200;
    QueryParams: GetTeamsMatchesJsonQueryParams;
    Errors: GetTeamsMatchesJson400 | GetTeamsMatchesJson401 | GetTeamsMatchesJson404 | GetTeamsMatchesJson500;
};