/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiError } from "./ApiError.ts";
import type { TranslationsResponse } from "./TranslationsResponse.ts";

export type GetTranslationsTeamsJsonQueryParams = {
    /**
     * @description ISO 639-1 код языка для перевода (например, `ru`)
     * @type string | undefined
    */
    lang?: string | undefined;
    /**
     * @description ID страны
     * @type integer | undefined
    */
    country_id?: number | undefined;
    /**
     * @description ID соревнования (или несколько через запятую)
    */
    competition_id?: (number | string) | undefined;
};

/**
 * @description Переводы (команды)
*/
export type GetTranslationsTeamsJson200 = TranslationsResponse;

/**
 * @description Некорректный запрос
*/
export type GetTranslationsTeamsJson400 = ApiError;

/**
 * @description Неавторизовано
*/
export type GetTranslationsTeamsJson401 = ApiError;

export type GetTranslationsTeamsJsonQueryResponse = GetTranslationsTeamsJson200;

export type GetTranslationsTeamsJsonQuery = {
    Response: GetTranslationsTeamsJson200;
    QueryParams: GetTranslationsTeamsJsonQueryParams;
    Errors: GetTranslationsTeamsJson400 | GetTranslationsTeamsJson401;
};