/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Match } from "./Match.ts";

export type GetTeamsHead2HeadJsonQueryParams = {
    /**
     * @description ID первой команды для сравнения (Head2Head)
     * @type integer
    */
    team1_id: number;
    /**
     * @description ID второй команды для сравнения (Head2Head)
     * @type integer
    */
    team2_id: number;
};

/**
 * @description OK – данные H2H получены
*/
export type GetTeamsHead2HeadJson200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @description Объект с результатами сравнения (состав и формат данных зависит от реализации API)
     * @type object | undefined
    */
    data?: {
        /**
         * @description Последние матчи между двумя командами
         * @type array | undefined
        */
        last_matches_between?: Match[] | undefined;
        /**
         * @description Последние матчи команды 1
         * @type array | undefined
        */
        team1_last_matches?: Match[] | undefined;
        /**
         * @description Последние матчи команды 2
         * @type array | undefined
        */
        team2_last_matches?: Match[] | undefined;
    } | undefined;
};

/**
 * @description Ошибка запроса
*/
export type GetTeamsHead2HeadJson400 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type string | undefined
    */
    error?: string | undefined;
};

/**
 * @description Неавторизован (неверные ключ или секрет)
*/
export type GetTeamsHead2HeadJson401 = unknown;

/**
 * @description Одна из команд не найдена
*/
export type GetTeamsHead2HeadJson404 = unknown;

/**
 * @description Внутренняя ошибка сервера
*/
export type GetTeamsHead2HeadJson500 = unknown;

export type GetTeamsHead2HeadJsonQueryResponse = GetTeamsHead2HeadJson200;

export type GetTeamsHead2HeadJsonQuery = {
    Response: GetTeamsHead2HeadJson200;
    QueryParams: GetTeamsHead2HeadJsonQueryParams;
    Errors: GetTeamsHead2HeadJson400 | GetTeamsHead2HeadJson401 | GetTeamsHead2HeadJson404 | GetTeamsHead2HeadJson500;
};