/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { Outcomes } from './Outcomes.ts'

export type LastMatchesResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type array | undefined
   */
  data?:
    | {
        /**
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @type string | undefined, date
         */
        date?: Date | undefined
        /**
         * @type string | undefined
         */
        home_name?: string | undefined
        /**
         * @type string | undefined
         */
        away_name?: string | undefined
        /**
         * @type string | undefined
         */
        score?: string | undefined
        /**
         * @type string | undefined
         */
        ht_score?: string | undefined
        /**
         * @type string | undefined
         */
        ft_score?: string | undefined
        /**
         * @type string
         */
        et_score?: (string | null) | undefined
        /**
         * @type integer | undefined
         */
        home_id?: number | undefined
        /**
         * @type integer | undefined
         */
        away_id?: number | undefined
        /**
         * @type integer | undefined
         */
        competition_id?: number | undefined
        /**
         * @type string
         */
        location?: (string | null) | undefined
        /**
         * @type string
         */
        scheduled?: (string | null) | undefined
        /**
         * @type object | undefined
         */
        competition?: Competition | undefined
        /**
         * @type object | undefined
         */
        outcomes?: Outcomes | undefined
      }[]
    | undefined
}
