/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Lineup } from './Lineup.ts'

export type LineupsResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type integer | undefined
         */
        match_id?: number | undefined
        /**
         * @type object | undefined
         */
        home?: Lineup | undefined
        /**
         * @type object | undefined
         */
        away?: Lineup | undefined
      }
    | undefined
}
