/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LineupPlayer = {
  /**
   * @type integer
   */
  player_id?: (number | null) | undefined
  /**
   * @type string | undefined
   */
  player_name?: string | undefined
  /**
   * @type integer
   */
  number?: (number | null) | undefined
  /**
   * @type string
   */
  position?: (string | null) | undefined
  /**
   * @type boolean
   */
  captain?: (boolean | null) | undefined
}
