/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LineupPlayer } from "./LineupPlayer.ts";

export type Lineup = {
    /**
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @type string | undefined
    */
    team_name?: string | undefined;
    /**
     * @type string
    */
    formation?: (string | null) | undefined;
    /**
     * @type string
    */
    coach?: (string | null) | undefined;
    /**
     * @type array | undefined
    */
    starting?: LineupPlayer[] | undefined;
    /**
     * @type array | undefined
    */
    substitutes?: LineupPlayer[] | undefined;
};