/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Состав команды на матч (стартовый состав и запасные)
*/
export type Lineup = {
    /**
     * @description Список основных (стартовых) игроков команды
     * @type array | undefined
    */
    starting_lineup?: {
        /**
         * @description ID игрока
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @description Имя игрока
         * @type string | undefined
        */
        name?: string | undefined;
        /**
         * @description Номер на футболке
         * @type integer | undefined
        */
        number?: number | undefined;
        /**
         * @description Амплуа/позиция игрока (например, G, D, M, F)
         * @type string | undefined
        */
        position?: string | undefined;
    }[] | undefined;
    /**
     * @description Список запасных игроков команды
     * @type array | undefined
    */
    substitutes?: {
        /**
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @type string | undefined
        */
        name?: string | undefined;
        /**
         * @type integer | undefined
        */
        number?: number | undefined;
        /**
         * @type string | undefined
        */
        position?: string | undefined;
    }[] | undefined;
    /**
     * @description Тренер команды (если известен)
     * @type object
    */
    coach?: ({
        /**
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @type string | undefined
        */
        name?: string | undefined;
    } | null) | undefined;
};