/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TeamStats } from './TeamStats.ts'

export type MatchStats = {
  /**
   * @type integer | undefined
   */
  match_id?: number | undefined
  /**
   * @type object | undefined
   */
  home?: TeamStats | undefined
  /**
   * @type object | undefined
   */
  away?: TeamStats | undefined
}
