/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Competition } from "./Competition.ts";
import type { Country } from "./Country.ts";
import type { Federation } from "./Federation.ts";
import type { Team } from "./Team.ts";

/**
 * @description Модель матча (live или завершённого)
*/
export type Match = {
    /**
     * @description ID матча (для live или завершённого; отличается от fixture_id)
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @description ID соответствующего запланированного матча (fixture) для этого матча. Может быть 0 или null, если матч не был в календаре (добавлен непосредственно перед началом)
     * @type integer
    */
    fixture_id?: (number | null) | undefined;
    /**
     * @description Дата проведения матча (UTC)
     * @type string | undefined, date
    */
    date?: Date | undefined;
    /**
     * @description Время начала матча (UTC)
     * @type string | undefined
    */
    time?: string | undefined;
    /**
     * @description Дата и время добавления матча в live-ленту (UTC)
     * @type string | undefined, date-time
    */
    added?: Date | undefined;
    /**
     * @description Дата и время последнего обновления данных матча (UTC)
     * @type string | undefined, date-time
    */
    last_changed?: Date | undefined;
    /**
     * @description Текущий статус матча (например, NOT STARTED, IN PLAY, HALF TIME BREAK, ADDED TIME, FINISHED, INSUFFICIENT DATA)
     * @type string | undefined
    */
    status?: string | undefined;
    /**
     * @description Отображение текущего игрового времени или стадии: число минут (идущая минута) либо специальные значения: `HT` (перерыв), `FT` (конец 90 минут), `AET` (после доп. времени), `AP` (после пенальти)
     * @type string
    */
    time_status?: (string | null) | undefined;
    /**
     * @type object | undefined
    */
    home?: Team | undefined;
    /**
     * @type object | undefined
    */
    away?: Team | undefined;
    /**
     * @type object | undefined
    */
    competition?: Competition | undefined;
    /**
     * @type object | undefined
    */
    country?: Country | undefined;
    /**
     * @type object | undefined
    */
    federation?: Federation | undefined;
    /**
     * @description Место проведения матча (стадион, город или страна)
     * @type string
    */
    location?: (string | null) | undefined;
    /**
     * @description Объект с текущими счетами по ходу матча и итогами по периодам (для live и завершённых матчей).
     * @type object | undefined
    */
    scores?: {
        /**
         * @description Текущий счёт матча (формат `число - число`)
         * @type string | undefined
        */
        score?: string | undefined;
        /**
         * @description Счёт после первого тайма (полувремени)
         * @type string | undefined
        */
        ht_score?: string | undefined;
        /**
         * @description Счёт после второго тайма (основного времени)
         * @type string | undefined
        */
        ft_score?: string | undefined;
        /**
         * @description Счёт после дополнительного времени (если было)
         * @type string | undefined
        */
        et_score?: string | undefined;
        /**
         * @description Счёт после серии пенальти (если была)
         * @type string | undefined
        */
        ps_score?: string | undefined;
    } | undefined;
    /**
     * @description Объект с исходами матча по результатам основных этапов (`1`, `X`, `2` для первой команды, ничьи или второй команды).
     * @type object | undefined
    */
    outcomes?: {
        /**
         * @description Исход после первого тайма (`1`, `X` или `2` либо null если недоступно)
         * @type string
        */
        half_time?: (string | null) | undefined;
        /**
         * @description Исход после основного времени (`1`, `X` или `2`)
         * @type string
        */
        full_time?: (string | null) | undefined;
        /**
         * @description Исход после доп. времени (`1`, `X` или `2`, для кубковых матчей)
         * @type string
        */
        extra_time?: (string | null) | undefined;
        /**
         * @description Исход после серии пенальти (`1` или `2`, ничья не применяется)
         * @type string
        */
        penalty_shootout?: (string | null) | undefined;
    } | undefined;
    /**
     * @description Объект с коэффициентами ставок на матч (прематчевые и live).
     * @type object | undefined
    */
    odds?: {
        /**
         * @description Коэффициенты перед началом матча (прематч) – для исходов 1, X, 2.
         * @type object | undefined
        */
        pre?: {
            /**
             * @description Коэффициент на победу первой (домашней) команды до матча
             * @type number | undefined
            */
            "1"?: number | undefined;
            /**
             * @description Коэффициент на победу второй (гостевой) команды до матча
             * @type number | undefined
            */
            "2"?: number | undefined;
            /**
             * @description Коэффициент на ничью до матча
             * @type number | undefined
            */
            X?: number | undefined;
        } | undefined;
        /**
         * @description Текущие live-коэффициенты (в режиме реального времени) для исходов 1, X, 2.
         * @type object | undefined
        */
        live?: {
            /**
             * @description Live-коэффициент на победу первой команды
             * @type number
            */
            "1"?: (number | null) | undefined;
            /**
             * @description Live-коэффициент на победу второй команды
             * @type number
            */
            "2"?: (number | null) | undefined;
            /**
             * @description Live-коэффициент на ничью
             * @type number
            */
            X?: (number | null) | undefined;
        } | undefined;
    } | undefined;
    /**
     * @description Связанные ссылки на подробные данные по матчу (эндпоинты внутри данного API). Поля:
     * @type object | undefined
    */
    urls?: {
        /**
         * @description URL для получения событий матча (голы, карточки и пр.)
         * @type string | undefined
        */
        events?: string | undefined;
        /**
         * @description URL для получения статистики матча
         * @type string | undefined
        */
        statistics?: string | undefined;
        /**
         * @description URL для получения стартовых составов матча
         * @type string | undefined
        */
        lineups?: string | undefined;
        /**
         * @description URL для получения сравнения (H2H) двух команд, играющих в матче
         * @type string | undefined
        */
        head2head?: string | undefined;
    } | undefined;
};