/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Статистика матча: к��ючи объекта – наименования статистических показателей, значения – строки вида `\"Дома:Гости\"` (либо `null`, если данные недоступны).
 */
export type MatchStats = {
  /**
   * @description Количество атак (home:away)
   * @type string | undefined
   */
  attacks?: string | undefined
  /**
   * @description Количество опасных атак (home:away)
   * @type string | undefined
   */
  dangerous_attacks?: string | undefined
  /**
   * @description Владение мячом в процентах (home:away, сумма = 100%)
   * @type string | undefined
   */
  possession?: string | undefined
  /**
   * @description Удары в створ ворот (home:away)
   * @type string | undefined
   */
  shots_on_target?: string | undefined
  /**
   * @description Удары мимо ворот (home:away)
   * @type string | undefined
   */
  shots_off_target?: string | undefined
  /**
   * @description Заблокированные удары (home:away)
   * @type string | undefined
   */
  shots_blocked?: string | undefined
  /**
   * @description Все попытки удара по воротам (home:away), сумма ударов в створ и мимо
   * @type string | undefined
   */
  attempts_on_goal?: string | undefined
  /**
   * @description Угловые удары (home:away)
   * @type string | undefined
   */
  corners?: string | undefined
  /**
   * @description Офсайды (положения «вне игры») (home:away)
   * @type string | undefined
   */
  offsides?: string | undefined
  /**
   * @description Жёлтые карточки (home:away)
   * @type string | undefined
   */
  yellow_cards?: string | undefined
  /**
   * @description Красные карточки (home:away)
   * @type string | undefined
   */
  red_cards?: string | undefined
  /**
   * @description Проведённые замены (home:away)
   * @type string | undefined
   */
  substitutions?: string | undefined
  /**
   * @description Нарушения правил (фолы) (home:away)
   * @type string | undefined
   */
  fouls?: string | undefined
  /**
   * @description Штрафные удары (home:away)
   * @type string | undefined
   */
  free_kicks?: string | undefined
  /**
   * @description Удары от ворот (home:away)
   * @type string | undefined
   */
  goal_kicks?: string | undefined
  /**
   * @description Вбрасывания (ауты) (home:away)
   * @type string | undefined
   */
  throw_ins?: string | undefined
  /**
   * @description Сэйвы вратаря (home:away)
   * @type string | undefined
   */
  saves?: string | undefined
  /**
   * @description Оказания медицинской помощи на поле (home:away)
   * @type string | undefined
   */
  treatments?: string | undefined
  /**
   * @description Пенальти (назначенные) (home:away)
   * @type string | undefined
   */
  penalties?: string | undefined
}
