/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Competition } from "./Competition.ts";
import type { Odds } from "./Odds.ts";
import type { Outcomes } from "./Outcomes.ts";
import type { Score } from "./Score.ts";
import type { Team } from "./Team.ts";

/**
 * @description Универсальная модель матча (live/история)
*/
export type Match = {
    /**
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @description ID связанной фикстуры (если есть)
     * @type integer
    */
    fixture_id?: (number | null) | undefined;
    /**
     * @type object | undefined
    */
    competition?: Competition | undefined;
    /**
     * @type string | undefined, date
    */
    date?: Date | undefined;
    /**
     * @type string | undefined
    */
    time?: string | undefined;
    /**
     * @type string | undefined
    */
    status?: string | undefined;
    /**
     * @type string
    */
    round?: (string | null) | undefined;
    /**
     * @type integer
    */
    group_id?: (number | null) | undefined;
    /**
     * @type object | undefined
    */
    home?: Team | undefined;
    /**
     * @type object | undefined
    */
    away?: Team | undefined;
    /**
     * @type object | undefined
    */
    scores?: Score | undefined;
    /**
     * @type string
    */
    time_elapsed?: (string | null) | undefined;
    /**
     * @type string
    */
    location?: (string | null) | undefined;
    /**
     * @type object | undefined
    */
    odds?: Odds | undefined;
    /**
     * @type object | undefined
    */
    outcomes?: Outcomes | undefined;
    /**
     * @type object | undefined
    */
    urls?: {
        /**
         * @type string, uri
        */
        events?: (string | null) | undefined;
        /**
         * @type string, uri
        */
        statistics?: (string | null) | undefined;
        /**
         * @type string, uri
        */
        lineups?: (string | null) | undefined;
        /**
         * @type string, uri
        */
        head2head?: (string | null) | undefined;
    } | undefined;
};