/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OddsOneXTwo } from './OddsOneXTwo.ts'

export type Odds = {
  /**
   * @type object | undefined
   */
  pre?: OddsOneXTwo | undefined
  /**
   * @type object | undefined
   */
  live?: OddsOneXTwo | undefined
}
