/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OddsOneXTwo } from './OddsOneXTwo.ts'

export type OddsResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type array | undefined
   */
  data?:
    | {
        /**
         * @type integer | undefined
         */
        match_id?: number | undefined
        /**
         * @type integer | undefined
         */
        competition_id?: number | undefined
        /**
         * @type string | undefined, date
         */
        date?: Date | undefined
        /**
         * @type string | undefined
         */
        time?: string | undefined
        /**
         * @type integer | undefined
         */
        home_id?: number | undefined
        /**
         * @type integer | undefined
         */
        away_id?: number | undefined
        /**
         * @type object | undefined
         */
        odds?: OddsOneXTwo | undefined
      }[]
    | undefined
}
