/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type OddsOneXTwo = {
    /**
     * @type number
    */
    "1"?: (number | null) | undefined;
    /**
     * @type number
    */
    "2"?: (number | null) | undefined;
    /**
     * @type number
    */
    X?: (number | null) | undefined;
};