/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Outcomes = {
    /**
     * @type string
    */
    half_time?: (string | null) | undefined;
    /**
     * @type string
    */
    full_time?: (string | null) | undefined;
    /**
     * @type string
    */
    extra_time?: (string | null) | undefined;
    /**
     * @type string
    */
    penalty_shootout?: (string | null) | undefined;
};