/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Pagination = {
    /**
     * @type integer | undefined
    */
    page?: number | undefined;
    /**
     * @type integer | undefined
    */
    size?: number | undefined;
    /**
     * @type integer | undefined
    */
    total_pages?: number | undefined;
    /**
     * @type integer | undefined
    */
    total_items?: number | undefined;
};