/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Score = {
    /**
     * @type string
    */
    score?: (string | null) | undefined;
    /**
     * @type string
    */
    ht_score?: (string | null) | undefined;
    /**
     * @type string
    */
    ft_score?: (string | null) | undefined;
    /**
     * @type string
    */
    et_score?: (string | null) | undefined;
    /**
     * @type string
    */
    ps_score?: (string | null) | undefined;
};