/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SeasonRef = {
  /**
   * @type integer | undefined
   */
  id?: number | undefined
  /**
   * @type string | undefined
   */
  name?: string | undefined
  /**
   * @type string | undefined, date
   */
  start?: Date | undefined
  /**
   * @type string | undefined, date
   */
  end?: Date | undefined
}
