/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SeasonRef } from './SeasonRef.ts'

export type SeasonsResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type array | undefined
         */
        seasons?: SeasonRef[] | undefined
      }
    | undefined
}
