/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Игрок в заявке команды на соревнование (предварительный состав на турнир)
*/
export type SquadPlayer = {
    /**
     * @description ID игрока
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @description Имя игрока
     * @type string | undefined
    */
    name?: string | undefined;
    /**
     * @description Номер игрока в заявке (на футболке на турнире)
     * @type integer | undefined
    */
    shirt_number?: number | undefined;
    /**
     * @description Амплуа игрока (GK – вратарь, DF – защитник, MF – полузащитник, FW – нападающий)
     * @type string | undefined
    */
    position?: string | undefined;
};