/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TableRow = {
    /**
     * @type integer
    */
    competition_id?: (number | null) | undefined;
    /**
     * @type integer
    */
    group_id?: (number | null) | undefined;
    /**
     * @type string
    */
    group_name?: (string | null) | undefined;
    /**
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @type string | undefined
    */
    team_name?: string | undefined;
    /**
     * @type integer | undefined
    */
    rank?: number | undefined;
    /**
     * @type integer | undefined
    */
    matches?: number | undefined;
    /**
     * @type integer | undefined
    */
    won?: number | undefined;
    /**
     * @type integer | undefined
    */
    drawn?: number | undefined;
    /**
     * @type integer | undefined
    */
    lost?: number | undefined;
    /**
     * @type integer | undefined
    */
    goals_scored?: number | undefined;
    /**
     * @type integer | undefined
    */
    goals_conceded?: number | undefined;
    /**
     * @type integer | undefined
    */
    goal_diff?: number | undefined;
    /**
     * @type integer | undefined
    */
    points?: number | undefined;
    /**
     * @description Последние результаты (например, [\'W\',\'D\',\'L\',\'W\',\'W\',\'D\'])
     * @type array
    */
    form?: (string[] | null) | undefined;
};