/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Строка таблицы (позиция команды в турнирной таблице)
*/
export type TableRow = {
    /**
     * @description Место (позиция) команды в таблице
     * @type integer | undefined
    */
    rank?: number | undefined;
    /**
     * @description ID команды
     * @type integer | undefined
    */
    team_id?: number | undefined;
    /**
     * @description Название команды
     * @type string | undefined
    */
    team_name?: string | undefined;
    /**
     * @description Количество сыгранных матчей
     * @type integer | undefined
    */
    matches?: number | undefined;
    /**
     * @description Выиг��ыши (количество побед)
     * @type integer | undefined
    */
    won?: number | undefined;
    /**
     * @description Ничьи (количество)
     * @type integer | undefined
    */
    drawn?: number | undefined;
    /**
     * @description Поражения (количество)
     * @type integer | undefined
    */
    lost?: number | undefined;
    /**
     * @description Забитые голы
     * @type integer | undefined
    */
    goals_for?: number | undefined;
    /**
     * @description Пропущенные голы
     * @type integer | undefined
    */
    goals_against?: number | undefined;
    /**
     * @description Разница голов (забитые минус пропущенные)
     * @type integer | undefined
    */
    goal_diff?: number | undefined;
    /**
     * @description Очки
     * @type integer | undefined
    */
    points?: number | undefined;
    /**
     * @description Последние результаты команды (серия из ~5 символов: W - победа, D - ничья, L - поражение) при запросе с include_form=1
     * @type string
    */
    form?: (string | null) | undefined;
};