/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { SeasonRef } from './SeasonRef.ts'
import type { TableRow } from './TableRow.ts'

export type TableResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type object | undefined
         */
        competition?: Competition | undefined
        /**
         * @type object | undefined
         */
        season?: SeasonRef | undefined
        /**
         * @description Таблица (список строк). Если лига с группами — возможны несколько групп через group_id/group_name.
         * @type array | undefined
         */
        standings?: TableRow[] | undefined
      }
    | undefined
}
