/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pagination } from "./Pagination.ts";
import type { Team } from "./Team.ts";

export type TeamsResponse = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type array | undefined
        */
        teams?: Team[] | undefined;
        /**
         * @type object | undefined
        */
        pagination?: Pagination | undefined;
    } | undefined;
};