/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TeamStats = {
    /**
     * @type number
    */
    possession?: (number | null) | undefined;
    /**
     * @type integer
    */
    shots_total?: (number | null) | undefined;
    /**
     * @type integer
    */
    shots_on_target?: (number | null) | undefined;
    /**
     * @type integer
    */
    shots_off_target?: (number | null) | undefined;
    /**
     * @type integer
    */
    corners?: (number | null) | undefined;
    /**
     * @type integer
    */
    offsides?: (number | null) | undefined;
    /**
     * @type integer
    */
    fouls?: (number | null) | undefined;
    /**
     * @type integer
    */
    yellow_cards?: (number | null) | undefined;
    /**
     * @type integer
    */
    red_cards?: (number | null) | undefined;
    /**
     * @type integer
    */
    passes_total?: (number | null) | undefined;
    /**
     * @type number
    */
    passes_accuracy?: (number | null) | undefined;
};