/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Country } from './Country.ts'

export type Team = {
  /**
   * @type integer | undefined
   */
  id?: number | undefined
  /**
   * @type string | undefined
   */
  name?: string | undefined
  /**
   * @type string
   */
  short_code?: (string | null) | undefined
  /**
   * @type integer
   */
  country_id?: (number | null) | undefined
  /**
   * @type object | undefined
   */
  country?: Country | undefined
  /**
   * @description URL логотипа (если доступно)
   * @type string, uri
   */
  logo?: (string | null) | undefined
  /**
   * @type string
   */
  stadium?: (string | null) | undefined
}
