/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Country } from "./Country.ts";

export type Team = {
    /**
     * @description Уникальный ID команды
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @description Название команды
     * @type string | undefined
    */
    name?: string | undefined;
    /**
     * @description ID страны, к которой привязана команда (для клубов)
     * @type integer
    */
    country_id?: (number | null) | undefined;
    /**
     * @type object | undefined
    */
    country?: Country | undefined;
    /**
     * @description Название стадиона (домашнего поля) команды (если есть данные)
     * @type string
    */
    stadium?: (string | null) | undefined;
    /**
     * @description URL логотипа команды (PNG изображение на CDN)
     * @type string, uri
    */
    logo?: (string | null) | undefined;
};