/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Запись о наиболее \"дисциплинарно наказанном\" игроке (карточки).
 */
export type TopCardEntry = {
  /**
   * @description Объект игрока
   * @type object | undefined
   */
  player?:
    | {
        /**
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @type string | undefined
         */
        name?: string | undefined
      }
    | undefined
  /**
   * @description Объект команды игрока
   * @type object | undefined
   */
  team?:
    | {
        /**
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @type string | undefined
         */
        name?: string | undefined
        /**
         * @type string
         */
        stadium?: (string | null) | undefined
        /**
         * @type integer | undefined
         */
        country_id?: number | undefined
        /**
         * @type string
         */
        logo?: (string | null) | undefined
      }
    | undefined
  /**
   * @description Количество жёлтых карточек, полученных игроком
   * @type integer | undefined
   */
  yellow_cards?: number | undefined
  /**
   * @description Количество красных карточек, полученных игроком
   * @type integer | undefined
   */
  red_cards?: number | undefined
  /**
   * @description Количество матчей, в которых игрок участвовал
   * @type integer | undefined
   */
  played?: number | undefined
}
