/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Запись о бомбардире (игроке) в списке лучших бомбардиров.
 */
export type TopScorerEntry = {
  /**
   * @description Объект игрока (лучшего бомбардира)
   * @type object | undefined
   */
  player?:
    | {
        /**
         * @description ID игрока
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @description Имя игрока
         * @type string | undefined
         */
        name?: string | undefined
      }
    | undefined
  /**
   * @description Объект команды, за которую выступает игрок
   * @type object | undefined
   */
  team?:
    | {
        /**
         * @description ID команды
         * @type integer | undefined
         */
        id?: number | undefined
        /**
         * @description Название команды
         * @type string | undefined
         */
        name?: string | undefined
        /**
         * @description Стадион команды (если применимо)
         * @type string
         */
        stadium?: (string | null) | undefined
        /**
         * @description ID страны команды
         * @type integer | undefined
         */
        country_id?: number | undefined
      }
    | undefined
  /**
   * @description Количество голов, забитых игроком в сезоне
   * @type integer | undefined
   */
  goals?: number | undefined
  /**
   * @description Количество результативных передач игрока
   * @type integer | undefined
   */
  assists?: number | undefined
  /**
   * @description Количество матчей, в которых игрок участвовал
   * @type integer | undefined
   */
  played?: number | undefined
}
