/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Competition } from './Competition.ts'
import type { Team } from './Team.ts'

export type TopScorersResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type object | undefined
         */
        competition?: Competition | undefined
        /**
         * @type array | undefined
         */
        topscorers?:
          | {
              /**
               * @type integer | undefined
               */
              goals?: number | undefined
              /**
               * @type integer
               */
              assists?: (number | null) | undefined
              /**
               * @type integer | undefined
               */
              played?: number | undefined
              /**
               * @type object | undefined
               */
              team?: Team | undefined
              /**
               * @type object | undefined
               */
              player?:
                | {
                    /**
                     * @type integer | undefined
                     */
                    id?: number | undefined
                    /**
                     * @type string | undefined
                     */
                    name?: string | undefined
                  }
                | undefined
            }[]
          | undefined
      }
    | undefined
}
