/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TranslationsResponse = {
    /**
     * @type boolean | undefined
    */
    success?: boolean | undefined;
    /**
     * @type array | undefined
    */
    data?: {
        /**
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @type string | undefined
        */
        name_en?: string | undefined;
        /**
         * @description Название на языке `lang`
         * @type string | undefined
        */
        name_localized?: string | undefined;
    }[] | undefined;
};