/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type VerifyResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean | undefined
  /**
   * @type object | undefined
   */
  data?:
    | {
        /**
         * @type string | undefined
         */
        plan?: string | undefined
        /**
         * @type integer | undefined
         */
        endpoints_left?: number | undefined
      }
    | undefined
}
