/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesStatsJsonQueryResponse, GetMatchesStatsJsonQueryParams, GetMatchesStatsJson400, GetMatchesStatsJson401, GetMatchesStatsJson404, GetMatchesStatsJson500 } from "../../types/GetMatchesStatsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesStatsJsonUrl() {
  const res = { method: 'GET', url: `/matches/stats.json` as const }  
  return res
}

/**
 * @summary Статистика матча
 * {@link /matches/stats.json}
 */
export async function getMatchesStatsJson(params: GetMatchesStatsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesStatsJsonQueryResponse, ResponseErrorConfig<GetMatchesStatsJson400 | GetMatchesStatsJson401 | GetMatchesStatsJson404 | GetMatchesStatsJson500>, unknown>({ method : "GET", url : getGetMatchesStatsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}