/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesStatsJsonQueryResponse, GetMatchesStatsJsonQueryParams, GetMatchesStatsJson400, GetMatchesStatsJson401, GetMatchesStatsJson404, GetMatchesStatsJson500 } from "../../types/GetMatchesStatsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesStatsJsonUrl() {
  const res = { method: 'GET', url: `/matches/stats.json` as const }  
  return res
}

/**
 * @description Возвращает основные статистические показатели указанного матча (для обеих команд). Матч должен быть уже начат или завершён; для предстоящих матчей статистика недоступна.  **Замечание:** не для всех матчей доступны абсолютно все виды статистики – для некоторых менее крупных соревнований некоторые поля могут быть `null` или отсутствовать вовсе.  В возвращаемом объекте статистики ключами являются названия метрик (на англ.), а значениями – строка формата `"домашние:гости"` (например, `"shots_on_target": "5:3"`), либо null, если данные отсутствуют.  **Пример запроса:**  `GET /matches/stats.json?match_id=172252&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Статистика матча
 * {@link /matches/stats.json}
 */
export async function getMatchesStatsJson(params: GetMatchesStatsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesStatsJsonQueryResponse, ResponseErrorConfig<GetMatchesStatsJson400 | GetMatchesStatsJson401 | GetMatchesStatsJson404 | GetMatchesStatsJson500>, unknown>({ method : "GET", url : getGetMatchesStatsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}