/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesLineupsJsonQueryResponse, GetMatchesLineupsJsonQueryParams, GetMatchesLineupsJson400, GetMatchesLineupsJson401, GetMatchesLineupsJson404, GetMatchesLineupsJson500 } from "../../types/GetMatchesLineupsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesLineupsJsonUrl() {
  const res = { method: 'GET', url: `/matches/lineups.json` as const }  
  return res
}

/**
 * @summary Стартовые составы матча
 * {@link /matches/lineups.json}
 */
export async function getMatchesLineupsJson(params: GetMatchesLineupsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesLineupsJsonQueryResponse, ResponseErrorConfig<GetMatchesLineupsJson400 | GetMatchesLineupsJson401 | GetMatchesLineupsJson404 | GetMatchesLineupsJson500>, unknown>({ method : "GET", url : getGetMatchesLineupsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}