/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetTeamsHead2HeadJsonQueryResponse, GetTeamsHead2HeadJsonQueryParams, GetTeamsHead2HeadJson400, GetTeamsHead2HeadJson401, GetTeamsHead2HeadJson404, GetTeamsHead2HeadJson500 } from "../../types/GetTeamsHead2HeadJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetTeamsHead2HeadJsonUrl() {
  const res = { method: 'GET', url: `/teams/head2head.json` as const }  
  return res
}

/**
 * @summary Очные встречи (H2H) двух команд
 * {@link /teams/head2head.json}
 */
export async function getTeamsHead2HeadJson(params: GetTeamsHead2HeadJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetTeamsHead2HeadJsonQueryResponse, ResponseErrorConfig<GetTeamsHead2HeadJson400 | GetTeamsHead2HeadJson401 | GetTeamsHead2HeadJson404 | GetTeamsHead2HeadJson500>, unknown>({ method : "GET", url : getGetTeamsHead2HeadJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}