/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getMatchesLineupsJson } from './getMatchesLineupsJson.ts'
import { getMatchesStatsJson } from './getMatchesStatsJson.ts'
import { getTeamsHead2HeadJson } from './getTeamsHead2HeadJson.ts'

export function lineupsStatsService() {
  return { getMatchesLineupsJson, getMatchesStatsJson, getTeamsHead2HeadJson }
}
