/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getMatchesLineupsJson } from './getMatchesLineupsJson.ts'
import { getMatchesStatsJson } from './getMatchesStatsJson.ts'

export function lineupsStatsService() {
  return { getMatchesLineupsJson, getMatchesStatsJson }
}
