/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const operations = {
  "get_matches-live-json": {
    "path": "/matches/live.json",
    "method": "get"
  },
  "get_matches-history-json": {
    "path": "/matches/history.json",
    "method": "get"
  },
  "get_fixtures-matches-json": {
    "path": "/fixtures/matches.json",
    "method": "get"
  },
  "get_matches-events-json": {
    "path": "/matches/events.json",
    "method": "get"
  },
  "get_matches-lineups-json": {
    "path": "/matches/lineups.json",
    "method": "get"
  },
  "get_matches-stats-json": {
    "path": "/matches/stats.json",
    "method": "get"
  },
  "get_odds-pre-json": {
    "path": "/odds/pre.json",
    "method": "get"
  },
  "get_odds-live-json": {
    "path": "/odds/live.json",
    "method": "get"
  },
  "get_tables-standings-json": {
    "path": "/tables/standings.json",
    "method": "get"
  },
  "get_competitions-topscorers-json": {
    "path": "/competitions/topscorers.json",
    "method": "get"
  },
  "get_teams-list-json": {
    "path": "/teams/list.json",
    "method": "get"
  },
  "get_competitions-list-json": {
    "path": "/competitions/list.json",
    "method": "get"
  },
  "get_countries-list-json": {
    "path": "/countries/list.json",
    "method": "get"
  },
  "get_federations-list-json": {
    "path": "/federations/list.json",
    "method": "get"
  },
  "get_seasons-list-json": {
    "path": "/seasons/list.json",
    "method": "get"
  },
  "get_teams-lastmatches-json": {
    "path": "/teams/lastmatches.json",
    "method": "get"
  },
  "get_teams-head2head-json": {
    "path": "/teams/head2head.json",
    "method": "get"
  },
  "get_translations-teams-json": {
    "path": "/translations/teams.json",
    "method": "get"
  },
  "get_translations-competitions-json": {
    "path": "/translations/competitions.json",
    "method": "get"
  },
  "get_translations-countries-json": {
    "path": "/translations/countries.json",
    "method": "get"
  },
  "get_translations-federations-json": {
    "path": "/translations/federations.json",
    "method": "get"
  },
  "get_countries-flag-json": {
    "path": "/countries/flag.json",
    "method": "get"
  },
  "get_auth-verify-json": {
    "path": "/auth/verify.json",
    "method": "get"
  }
} as const