/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetOddsPreJsonQueryResponse,
  GetOddsPreJsonQueryParams,
  GetOddsPreJson400,
  GetOddsPreJson401,
  GetOddsPreJson404,
  GetOddsPreJson500,
} from '../../types/GetOddsPreJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetOddsPreJsonUrl() {
  const res = { method: 'GET', url: `/odds/pre.json` as const }
  return res
}

/**
 * @summary Предматчевые коэффициенты (1X2)
 * {@link /odds/pre.json}
 */
export async function getOddsPreJson(
  params?: GetOddsPreJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetOddsPreJsonQueryResponse,
    ResponseErrorConfig<
      GetOddsPreJson400 | GetOddsPreJson401 | GetOddsPreJson404 | GetOddsPreJson500
    >,
    unknown
  >({ method: 'GET', url: getGetOddsPreJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
