/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetOddsLiveJsonQueryResponse,
  GetOddsLiveJsonQueryParams,
  GetOddsLiveJson400,
  GetOddsLiveJson401,
  GetOddsLiveJson404,
  GetOddsLiveJson500,
} from '../../types/GetOddsLiveJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetOddsLiveJsonUrl() {
  const res = { method: 'GET', url: `/odds/live.json` as const }
  return res
}

/**
 * @summary Лайв-коэффициенты (1X2)
 * {@link /odds/live.json}
 */
export async function getOddsLiveJson(
  params?: GetOddsLiveJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetOddsLiveJsonQueryResponse,
    ResponseErrorConfig<
      GetOddsLiveJson400 | GetOddsLiveJson401 | GetOddsLiveJson404 | GetOddsLiveJson500
    >,
    unknown
  >({ method: 'GET', url: getGetOddsLiveJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
