/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getOddsLiveJson } from './getOddsLiveJson.ts'
import { getOddsPreJson } from './getOddsPreJson.ts'

export function oddsService() {
  return { getOddsPreJson, getOddsLiveJson }
}
