/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getMatchesEventsJson } from "./getMatchesEventsJson.ts";

export function eventsService() {
  return { getMatchesEventsJson }
}