/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getScoresEventsJson } from './getScoresEventsJson.ts'

export function eventsService() {
  return { getScoresEventsJson }
}
