/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetMatchesEventsJsonQueryResponse, GetMatchesEventsJsonQueryParams, GetMatchesEventsJson400, GetMatchesEventsJson401, GetMatchesEventsJson404, GetMatchesEventsJson500 } from "../../types/GetMatchesEventsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetMatchesEventsJsonUrl() {
  const res = { method: 'GET', url: `/matches/events.json` as const }  
  return res
}

/**
 * @summary События матча
 * {@link /matches/events.json}
 */
export async function getMatchesEventsJson(params: GetMatchesEventsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMatchesEventsJsonQueryResponse, ResponseErrorConfig<GetMatchesEventsJson400 | GetMatchesEventsJson401 | GetMatchesEventsJson404 | GetMatchesEventsJson500>, unknown>({ method : "GET", url : getGetMatchesEventsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}