export type { ApiError } from "./types/ApiError.ts";
export type { Competition } from "./types/Competition.ts";
export type { Country } from "./types/Country.ts";
export type { Event } from "./types/Event.ts";
export type { Federation } from "./types/Federation.ts";
export type { Fixture } from "./types/Fixture.ts";
export type { GetAuthVerifyJson200, GetAuthVerifyJson400, GetAuthVerifyJson401, GetAuthVerifyJson404, GetAuthVerifyJson500, GetAuthVerifyJsonQueryResponse, GetAuthVerifyJsonQuery } from "./types/GetAuthVerifyJson.ts";
export type { Lineup } from "./types/Lineup.ts";
export type { Match } from "./types/Match.ts";
export type { MatchStats } from "./types/MatchStats.ts";
export type { SquadPlayer } from "./types/SquadPlayer.ts";
export type { TableRow } from "./types/TableRow.ts";
export type { Team } from "./types/Team.ts";
export type { TopCardEntry } from "./types/TopCardEntry.ts";
export type { TopScorerEntry } from "./types/TopScorerEntry.ts";
export { operations } from "./clients/operations.ts";
export { getGetAuthVerifyJsonUrl, getAuthVerifyJson } from "./clients/UtilityService/getAuthVerifyJson.ts";
export { utilityService } from "./clients/UtilityService/utilityService.ts";