/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetAuthVerifyJsonQueryResponse,
  GetAuthVerifyJson400,
  GetAuthVerifyJson401,
  GetAuthVerifyJson500,
} from '../../types/GetAuthVerifyJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetAuthVerifyJsonUrl() {
  const res = { method: 'GET', url: `/auth/verify.json` as const }
  return res
}

/**
 * @summary Проверка API-ключа и секрета
 * {@link /auth/verify.json}
 */
export async function getAuthVerifyJson(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetAuthVerifyJsonQueryResponse,
    ResponseErrorConfig<GetAuthVerifyJson400 | GetAuthVerifyJson401 | GetAuthVerifyJson500>,
    unknown
  >({ method: 'GET', url: getGetAuthVerifyJsonUrl().url.toString(), ...requestConfig })
  return res
}
