/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetCountriesFlagJsonQueryResponse, GetCountriesFlagJsonQueryParams, GetCountriesFlagJson400, GetCountriesFlagJson401, GetCountriesFlagJson404 } from "../../types/GetCountriesFlagJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetCountriesFlagJsonUrl() {
  const res = { method: 'GET', url: `/countries/flag.json` as const }  
  return res
}

/**
 * @summary Флаг национальной команды (PNG)
 * {@link /countries/flag.json}
 */
export async function getCountriesFlagJson(params: GetCountriesFlagJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCountriesFlagJsonQueryResponse, ResponseErrorConfig<GetCountriesFlagJson400 | GetCountriesFlagJson401 | GetCountriesFlagJson404>, unknown>({ method : "GET", url : getGetCountriesFlagJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}