/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetCountriesFlagPngQueryResponse,
  GetCountriesFlagPngQueryParams,
  GetCountriesFlagPng400,
  GetCountriesFlagPng401,
  GetCountriesFlagPng404,
  GetCountriesFlagPng500,
} from '../../types/GetCountriesFlagPng.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetCountriesFlagPngUrl() {
  const res = { method: 'GET', url: `/countries/flag.png` as const }
  return res
}

/**
 * @description Возвращает изображение флага запрошенной страны в формате PNG. Необходим идентификатор страны или ID национальной команды.  **Примечание:** Каждый вызов этого метода учитывается как отдельный запрос API, поэтому рекомендуется кэшировать полученные флаги на стороне клиента. Все флаги имеют фиксированную высоту ~240px, ширина зависит от пропорций флага.  **Параметры:** укажите либо `country_id` страны, либо `team_id` национальной сборной (оба варианта приводят к одному и тому же флагу, если команда является национальной сборной указанной страны).  **Пример запроса (флаг Австралии):**  `GET /countries/flag.png?country_id=71&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Флаг страны (изображение)
 * {@link /countries/flag.png}
 */
export async function getCountriesFlagPng(
  params?: GetCountriesFlagPngQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetCountriesFlagPngQueryResponse,
    ResponseErrorConfig<
      | GetCountriesFlagPng400
      | GetCountriesFlagPng401
      | GetCountriesFlagPng404
      | GetCountriesFlagPng500
    >,
    unknown
  >({ method: 'GET', url: getGetCountriesFlagPngUrl().url.toString(), params, ...requestConfig })
  return res
}
