/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getAuthVerifyJson } from "./getAuthVerifyJson.ts";

export function utilityService() {
  return { getAuthVerifyJson }
}