/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getAuthVerifyJson } from "./getAuthVerifyJson.ts";
import { getCountriesFlagJson } from "./getCountriesFlagJson.ts";

export function utilityService() {
  return { getCountriesFlagJson, getAuthVerifyJson }
}