/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getAuthVerifyJson } from './getAuthVerifyJson.ts'
import { getCountriesFlagPng } from './getCountriesFlagPng.ts'

export function utilityService() {
  return { getAuthVerifyJson, getCountriesFlagPng }
}
