/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetCompetitionsTopscorersJsonQueryResponse, GetCompetitionsTopscorersJsonQueryParams, GetCompetitionsTopscorersJson400, GetCompetitionsTopscorersJson401, GetCompetitionsTopscorersJson404, GetCompetitionsTopscorersJson500 } from "../../types/GetCompetitionsTopscorersJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetCompetitionsTopscorersJsonUrl() {
  const res = { method: 'GET', url: `/competitions/topscorers.json` as const }  
  return res
}

/**
 * @summary Лучшие бомбардиры соревнования
 * {@link /competitions/topscorers.json}
 */
export async function getCompetitionsTopscorersJson(params: GetCompetitionsTopscorersJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCompetitionsTopscorersJsonQueryResponse, ResponseErrorConfig<GetCompetitionsTopscorersJson400 | GetCompetitionsTopscorersJson401 | GetCompetitionsTopscorersJson404 | GetCompetitionsTopscorersJson500>, unknown>({ method : "GET", url : getGetCompetitionsTopscorersJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}