/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetCompetitionsTopcardsJsonQueryResponse, GetCompetitionsTopcardsJsonQueryParams, GetCompetitionsTopcardsJson400, GetCompetitionsTopcardsJson401, GetCompetitionsTopcardsJson404, GetCompetitionsTopcardsJson500 } from "../../types/GetCompetitionsTopcardsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetCompetitionsTopcardsJsonUrl() {
  const res = { method: 'GET', url: `/competitions/topcards.json` as const }  
  return res
}

/**
 * @description Возвращает список игроков, получивших наибольшее число карточек (жёлтых/красных) в указанном международном турнире. *Примечание:* данный эндпоинт работает **только для крупных международных турниров сборных** (ЧМ, ЧЕ, Копа Америка, Кубок Азии, Кубок Африки).  В ответе перечислены футболисты с указанием числа жёлтых и красных карточек. В остальном структура аналогична списку бомбардиров (competition, edition, season), однако поля `goals` и `assists` заменены на `yellow_cards` и `red_cards` соответственно.  **Параметры:**  - `competition_id` (обязательный) – ID турнира (только ID перечисленных международных турни��ов).  - `lang` (опционально) – код языка для перевода названий, аналогично другим методам.  **Пример запроса (дисциплинарный рейтинг ЧМ 2022, id=362):**  `GET /competitions/topcards.json?competition_id=362&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Антирекорд по карточкам (дисциплинарный рейтинг)
 * {@link /competitions/topcards.json}
 */
export async function getCompetitionsTopcardsJson(params?: GetCompetitionsTopcardsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCompetitionsTopcardsJsonQueryResponse, ResponseErrorConfig<GetCompetitionsTopcardsJson400 | GetCompetitionsTopcardsJson401 | GetCompetitionsTopcardsJson404 | GetCompetitionsTopcardsJson500>, unknown>({ method : "GET", url : getGetCompetitionsTopcardsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}