/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetCompetitionsStandingsJsonQueryResponse, GetCompetitionsStandingsJsonQueryParams, GetCompetitionsStandingsJson400, GetCompetitionsStandingsJson401, GetCompetitionsStandingsJson404, GetCompetitionsStandingsJson500 } from "../../types/GetCompetitionsStandingsJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetCompetitionsStandingsJsonUrl() {
  const res = { method: 'GET', url: `/competitions/standings.json` as const }  
  return res
}

/**
 * @description Возвращает турнирную таблицу (позиции команд) для указанного соревнования и сезона через рабочий endpoint /competitions/standings.json.Этот endpoint реально работает в отличие от /tables/standings.json который возвращает "Invalid module specified".**Параметры:**  - `competition_id` (обязательный) – ID соревнования, для которого запрашивается турнирная таблица.  - `season` (опциональный) – ID сезона. Если не указан, берётся текущий сезон соревнования.  - `group` или `group_id` (опционально) – можно указать имя группы или ID группы для турниров с группами.  - `include_form` (опциональный, 0/1) – если =1, в ответе для каждой команды будет добавлена форма (W/D/L результаты последних матчей).  - `lang` – код языка для локализации названий команд.  **Пример запроса (таблица РФПЛ, сезон 56):**  `GET /competitions/standings.json?competition_id=7&season=56&include_form=1&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Турнирная таблица соревнования (рабочий endpoint)
 * {@link /competitions/standings.json}
 */
export async function getCompetitionsStandingsJson(params?: GetCompetitionsStandingsJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCompetitionsStandingsJsonQueryResponse, ResponseErrorConfig<GetCompetitionsStandingsJson400 | GetCompetitionsStandingsJson401 | GetCompetitionsStandingsJson404 | GetCompetitionsStandingsJson500>, unknown>({ method : "GET", url : getGetCompetitionsStandingsJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}