/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTablesStandingsJsonQueryResponse,
  GetTablesStandingsJsonQueryParams,
  GetTablesStandingsJson400,
  GetTablesStandingsJson401,
  GetTablesStandingsJson404,
  GetTablesStandingsJson500,
} from '../../types/GetTablesStandingsJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTablesStandingsJsonUrl() {
  const res = { method: 'GET', url: `/tables/standings.json` as const }
  return res
}

/**
 * @summary Турнирная таблица (Standings)
 * {@link /tables/standings.json}
 */
export async function getTablesStandingsJson(
  params?: GetTablesStandingsJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTablesStandingsJsonQueryResponse,
    ResponseErrorConfig<
      | GetTablesStandingsJson400
      | GetTablesStandingsJson401
      | GetTablesStandingsJson404
      | GetTablesStandingsJson500
    >,
    unknown
  >({ method: 'GET', url: getGetTablesStandingsJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
