/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTablesStandingsJsonQueryResponse,
  GetTablesStandingsJsonQueryParams,
  GetTablesStandingsJson400,
  GetTablesStandingsJson401,
  GetTablesStandingsJson404,
  GetTablesStandingsJson500,
} from '../../types/GetTablesStandingsJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTablesStandingsJsonUrl() {
  const res = { method: 'GET', url: `/tables/standings.json` as const }
  return res
}

/**
 * @description Возвращает турнирную таблицу (позиции команд) для указанного соревнования и сезона. По умолчанию возвращаются текущие standings для активного сезона соревнования. Для соревнований с группами можно указать конкретную группу или групповой этап.  **Параметры:**  - `competition_id` (обязательный) – ID соревнования, для которого запрашивается турнирная таблица.  - `season` (опциональный) – ID сезона. Если не указан, берётся текущий сезон соревнования.  - `group` или `group_id` (опционально) – можно указать имя группы (например, A, B, C) либо ID группы, чтобы получить таблицу только этой группы (для турниров с группами, например Лига Чемпионов). Если не указано, для многогрупповых турниров может вернуться совокупная таблица или таблица первой группы.  - `include_form` (опциональный, 0/1) – если =1, в ответе для каждой команды будет добавлен массив/строка формы (W/D/L результаты последних матчей).  - `lang` – код языка для локализации названий команд (если доступно).  **Пример запроса (таблица АПЛ, сезон по умолчанию):**  `GET /tables/standings.json?competition_id=2&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Турнирная таблица соревнования (Standings)
 * {@link /tables/standings.json}
 */
export async function getTablesStandingsJson(
  params?: GetTablesStandingsJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTablesStandingsJsonQueryResponse,
    ResponseErrorConfig<
      | GetTablesStandingsJson400
      | GetTablesStandingsJson401
      | GetTablesStandingsJson404
      | GetTablesStandingsJson500
    >,
    unknown
  >({ method: 'GET', url: getGetTablesStandingsJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
