/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { getCompetitionsStandingsJson } from "./getCompetitionsStandingsJson.ts";
import { getCompetitionsTopcardsJson } from "./getCompetitionsTopcardsJson.ts";
import { getCompetitionsTopscorersJson } from "./getCompetitionsTopscorersJson.ts";
import { getTablesStandingsJson } from "./getTablesStandingsJson.ts";

export function tablesService() {
  return { getTablesStandingsJson, getCompetitionsStandingsJson, getCompetitionsTopscorersJson, getCompetitionsTopcardsJson }
}