/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    comments: Comment;
    commentVotes: CommentVote;
    leagues: League;
    matches: Match;
    matchStats: MatchStat;
    predictionStats: PredictionStat;
    'bet-markets': BetMarket;
    'outcome-groups': OutcomeGroup;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    commentVotes: CommentVotesSelect<false> | CommentVotesSelect<true>;
    leagues: LeaguesSelect<false> | LeaguesSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    matchStats: MatchStatsSelect<false> | MatchStatsSelect<true>;
    predictionStats: PredictionStatsSelect<false> | PredictionStatsSelect<true>;
    'bet-markets': BetMarketsSelect<false> | BetMarketsSelect<true>;
    'outcome-groups': OutcomeGroupsSelect<false> | OutcomeGroupsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    topMatchesLeagues: TopMatchesLeague;
    sidebarLeagues: SidebarLeague;
    'outcome-manager': OutcomeManager;
    'header-menu': HeaderMenu;
  };
  globalsSelect: {
    topMatchesLeagues: TopMatchesLeaguesSelect<false> | TopMatchesLeaguesSelect<true>;
    sidebarLeagues: SidebarLeaguesSelect<false> | SidebarLeaguesSelect<true>;
    'outcome-manager': OutcomeManagerSelect<false> | OutcomeManagerSelect<true>;
    'header-menu': HeaderMenuSelect<false> | HeaderMenuSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 👥 Управление пользователями
 *
 * Здесь вы можете просматривать и редактировать профили пользователей, назначать роли, управлять рейтингами и модерировать учётные записи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Роль определяет уровень доступа в системе
   */
  role: 'admin' | 'user';
  /**
   * Уникальный идентификатор для публичного профиля (используется в URL)
   */
  username?: string | null;
  /**
   * Отображаемое имя пользователя на сайте
   */
  name?: string | null;
  /**
   * Биография пользователя для публичного профиля
   */
  bio?: string | null;
  /**
   * Загрузите изображение профиля через медиабиблиотеку
   */
  avatar?: (string | null) | Media;
  /**
   * Альтернатива загруженному файлу - укажите прямую ссылку на изображение
   */
  avatarUrl?: string | null;
  /**
   * Ссылки на профили пользователя в социальных сетях
   */
  links?: {
    website?: string | null;
    twitter?: string | null;
    github?: string | null;
  };
  /**
   * Рейтинг пользователя на основе прогнозов (редактируется только администратором)
   */
  rating?: number | null;
  /**
   * Подтвердил ли пользователь свой email адрес
   */
  emailVerified?: boolean | null;
  /**
   * Служебное поле для верификации email
   */
  emailVerificationToken?: string | null;
  /**
   * Дата истечения токена подтверждения email
   */
  emailVerificationExpires?: string | null;
  /**
   * Служебное поле для восстановления пароля
   */
  passwordResetToken?: string | null;
  /**
   * Дата истечения токена сброса пароля
   */
  passwordResetExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * 🖼️ Библиотека медиафайлов
 *
 * Загружайте и управляйте изображениями для аватаров, обложек статей и других целей. Система автоматически создаёт миниатюры.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Описание изображения для SEO и доступности (отображается если картинка не загрузилась)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 📝 Публикации пользователей
 *
 * Создавайте и редактируйте публикации (посты и прогнозы). ��оддерживается rich-text редактор с форматированием.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * Название публикации (используется для генерации URL)
   */
  title: string;
  /**
   * Автоматически генерируется из заголовка при сохранении (с транслитерацией кириллицы)
   */
  slug?: string | null;
  /**
   * Определяет структуру и отображение публикации
   */
  postType: 'regular' | 'prediction';
  /**
   * Основной текст публикации (поддерживает форматирование)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Главное изображение публикации (отображается в превью)
   */
  featuredImage?: (string | null) | Media;
  /**
   * ID матча из внешнего API (LiveScore)
   */
  matchId?: number | null;
  /**
   * ID предстоящего матча из внешнего API
   */
  fixtureId?: number | null;
  prediction?: {
    /**
     * Прогноз исхода матча
     */
    outcome?: ('home' | 'draw' | 'away') | null;
    score?: {
      /**
       * Голы хозяев
       */
      home?: number | null;
      /**
       * Голы гостей
       */
      away?: number | null;
    };
    fouls?: {
      /**
       * Общее количество фолов
       */
      total?: number | null;
      overUnder?: ('over' | 'under') | null;
    };
    corners?: {
      /**
       * Общее количество угловых
       */
      total?: number | null;
      /**
       * Угловые хозяев
       */
      home?: number | null;
      /**
       * Угловые гостей
       */
      away?: number | null;
    };
    yellowCards?: {
      /**
       * Общее количество желтых карточек
       */
      total?: number | null;
      /**
       * Желтые карточки хозяев
       */
      home?: number | null;
      /**
       * Желтые карточки гостей
       */
      away?: number | null;
    };
    /**
     * Рекомендуется: структурированное хранение событий с энумами
     */
    events?:
      | {
          market:
            | 'main'
            | 'doubleChance'
            | 'btts'
            | 'total'
            | 'statOutcome'
            | 'statDoubleChance'
            | 'teamTotal'
            | 'handicap'
            | 'combo';
          /**
           * Область применения (для голов и основных рынков)
           */
          scope?: ('ft' | '1h' | '2h') | null;
          /**
           * Показатель (для статистических рынков)
           */
          stat?:
            | (
                | 'goals'
                | 'corners'
                | 'yellowCards'
                | 'redCards'
                | 'fouls'
                | 'throw_ins'
                | 'goal_kicks'
                | 'shotsOnTarget'
                | 'shots'
                | 'saves'
                | 'offsides'
                | 'substitutions'
              )
            | null;
          /**
           * Для market=main
           */
          outcome?: ('P1' | 'X' | 'P2') | null;
          /**
           * Для market=doubleChance/statDoubleChance
           */
          dc?: ('1X' | '12' | 'X2') | null;
          /**
           * Для market=btts
           */
          btts?: ('yes' | 'no') | null;
          /**
           * Для тоталов: market=total/teamTotal/combo
           */
          kind?: ('over' | 'under') | null;
          /**
           * Линия (если требуется рынком)
           */
          line?: number | null;
          /**
           * Для ИТ/фор
           */
          team?: ('home' | 'away') | null;
          /**
           * Для market=combo
           */
          comboDc?: ('1X' | 'X2') | null;
          /**
           * Для market=combo
           */
          comboKind?: ('over' | 'under') | null;
          /**
           * Коэффициент на событие
           */
          coefficient: number;
          /**
           * Человекочитаемое представление события (опционально)
           */
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Информация о матче на момент создания прогноза
     */
    matchInfo?: {
      /**
       * Название команды хозяев
       */
      home?: string | null;
      /**
       * Название команды гостей
       */
      away?: string | null;
      /**
       * Название турнира/лиги
       */
      competition?: string | null;
      /**
       * Дата матча
       */
      date?: string | null;
      /**
       * Время матча
       */
      time?: string | null;
    };
  };
  /**
   * Пользователь, создавший публикацию (автоматически заполняется при создании)
   */
  author: string | User;
  /**
   * Дата и время создания публикации
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 💬 Комментарии к публикациям
 *
 * Просматривайте и модерируйте комментарии пользователей. Поддерживается система вложенных ответов и голосования.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  /**
   * Публикация, к которой относится комментарий
   */
  post: string | Post;
  /**
   * Если это ответ на другой комментарий, укажите родительский комментарий
   */
  parent?: (string | null) | Comment;
  /**
   * Содержание комментария (обычный текст)
   */
  content: string;
  /**
   * Пользователь, написавший комментарий
   */
  author: string | User;
  /**
   * Количество положительных оценок (автоматически)
   */
  upvotes: number;
  /**
   * Количество отрицательных оценок (автоматически)
   */
  downvotes: number;
  /**
   * Итоговый рейтинг (upvotes - downvotes)
   */
  score: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * 👍 Система голосования за комментарии
 *
 * Управляйте голосами пользователей за комментарии. Система автоматически подсчитывает рейтинг.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commentVotes".
 */
export interface CommentVote {
  id: string;
  comment: string | Comment;
  user: string | User;
  /**
   * 1 — плюс, -1 — минус
   */
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚽ Футбольные лиги и турниры
 *
 * Управляйте списком футбольных лиг и турниров. Данные обычно импортируются автоматически из внешних источников.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leagues".
 */
export interface League {
  id: string;
  /**
   * ID соревнования из внешнего API
   */
  competitionId: number;
  /**
   * Внешний идентификатор (если отличается от competitionId)
   */
  externalId?: string | null;
  /**
   * Оригинальное название лиги из API
   */
  name: string;
  /**
   * Пользовательское название лиги (переводы, сокращения и т.д.)
   */
  customName?: string | null;
  displayName?: string | null;
  /**
   * ID страны первого вхождения (если применимо)
   */
  countryId?: number | null;
  /**
   * Название страны (первое вхождение из списка стран)
   */
  countryName?: string | null;
  isLeague?: boolean | null;
  isCup?: boolean | null;
  /**
   * Дивизион (1 — высший)
   */
  tier?: number | null;
  hasGroups?: boolean | null;
  active?: boolean | null;
  /**
   * Только национальные сборные
   */
  nationalTeamsOnly?: boolean | null;
  /**
   * Страны, относящиеся к соревнованию
   */
  countries?:
    | {
        id: number;
        name: string;
      }[]
    | null;
  /**
   * Федерации, относящиеся к соревнованию
   */
  federations?:
    | {
        id: number;
        name: string;
      }[]
    | null;
  /**
   * Текущий сезон
   */
  season?: {
    id?: number | null;
    name?: string | null;
    start?: string | null;
    end?: string | null;
  };
  /**
   * Меньше — выше приоритет
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ⚽ База данных футбольных матчей
 *
 * Просматривайте информацию о матчах (прошлых, текущих, предс��оящих). Данные синхронизируются с внешним API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: string;
  /**
   * ID матча из внешнего API
   */
  matchId: number;
  /**
   * ID фикстуры из внешнего API (если отличается от matchId)
   */
  fixtureId?: number | null;
  /**
   * Дополнительный внешний идентификатор
   */
  externalId?: string | null;
  displayName?: string | null;
  /**
   * Дата матча (ISO-8601, UTC)
   */
  date: string;
  status: 'scheduled' | 'live' | 'halftime' | 'finished' | 'cancelled' | 'postponed' | 'suspended';
  /**
   * Минута матча (для live)
   */
  minute?: number | null;
  period?: ('not_started' | 'first_half' | 'halftime' | 'second_half' | 'extra_time' | 'penalties' | 'finished') | null;
  /**
   * Строка времени из API (например, FT)
   */
  time?: string | null;
  /**
   * Плановое время начала (например, 00:30)
   */
  scheduled?: string | null;
  /**
   * Время добавления матча в провайдере
   */
  addedAt?: string | null;
  /**
   * Время последнего изменения в провайдере
   */
  lastChangedAt?: string | null;
  /**
   * Название команды хозяев
   */
  homeTeam: string;
  /**
   * ID команды хозяев из API
   */
  homeTeamId?: number | null;
  /**
   * URL логотипа хозяев
   */
  homeLogo?: string | null;
  /**
   * Страна хозяев (ID)
   */
  homeCountryId?: number | null;
  /**
   * Стадион хозяев (из API)
   */
  homeStadium?: string | null;
  /**
   * Название команды гостей
   */
  awayTeam: string;
  /**
   * ID команды гостей из API
   */
  awayTeamId?: number | null;
  /**
   * URL логотипа гостей
   */
  awayLogo?: string | null;
  /**
   * Страна гостей (ID)
   */
  awayCountryId?: number | null;
  /**
   * Стадион гостей (из API)
   */
  awayStadium?: string | null;
  /**
   * Голы хозяев
   */
  homeScore?: number | null;
  /**
   * Голы гостей
   */
  awayScore?: number | null;
  /**
   * Голы хозяев к перерыву
   */
  homeScoreHalftime?: number | null;
  /**
   * Голы гостей к перерыву
   */
  awayScoreHalftime?: number | null;
  /**
   * Голы хозяев в доп. время
   */
  homeScoreExtraTime?: number | null;
  /**
   * Голы гостей в доп. время
   */
  awayScoreExtraTime?: number | null;
  /**
   * Голы хозяев в серии пенальти
   */
  homeScorePenalties?: number | null;
  /**
   * Голы гостей в серии пенальти
   */
  awayScorePenalties?: number | null;
  /**
   * Исходные строковые значения счёта из API
   */
  scoresRaw?: {
    score?: string | null;
    htScore?: string | null;
    ftScore?: string | null;
    etScore?: string | null;
    psScore?: string | null;
  };
  /**
   * Название соревнования
   */
  competition?: string | null;
  /**
   * ID соревнования из API
   */
  competitionId?: number | null;
  /**
   * Доп. детали соревнования из API
   */
  competitionDetails?: {
    isCup?: boolean | null;
    isLeague?: boolean | null;
    hasGroups?: boolean | null;
    nationalTeamsOnly?: boolean | null;
    active?: boolean | null;
    tier?: number | null;
  };
  /**
   * Федерация (если есть)
   */
  federation?: {
    federationId?: number | null;
    name?: string | null;
  };
  /**
   * Страна матча (если есть)
   */
  country?: {
    countryId?: number | null;
    name?: string | null;
    flag?: string | null;
    fifaCode?: string | null;
    uefaCode?: string | null;
    isReal?: boolean | null;
  };
  /**
   * Группа/подгруппа (если есть)
   */
  groupId?: number | null;
  /**
   * Связь с лигой из нашей базы
   */
  league?: (string | null) | League;
  /**
   * Информация о сезоне
   */
  season?: {
    seasonId?: number | null;
    name?: string | null;
    year?: string | null;
  };
  /**
   * Тур/раунд соревнования
   */
  round?: string | null;
  /**
   * Локация из API (строка)
   */
  location?: string | null;
  /**
   * Информация о стадионе
   */
  venue?: {
    name?: string | null;
    city?: string | null;
    country?: string | null;
  };
  /**
   * Главный судья
   */
  referee?: string | null;
  /**
   * Исходы из API (строки: 1/X/2)
   */
  outcomes?: {
    halfTime?: string | null;
    fullTime?: string | null;
    extraTime?: string | null;
    penaltyShootout?: string | null;
  };
  /**
   * Коэффициенты
   */
  odds?: {
    pre?: {
      home?: number | null;
      draw?: number | null;
      away?: number | null;
    };
    live?: {
      home?: number | null;
      draw?: number | null;
      away?: number | null;
    };
  };
  /**
   * Ссылки на события/статистику/составы/Н2Н
   */
  urls?: {
    events?: string | null;
    statistics?: string | null;
    lineups?: string | null;
    head2head?: string | null;
  };
  /**
   * Время последней синхронизации
   */
  lastSyncAt?: string | null;
  /**
   * Источник данных
   */
  syncSource?: ('history' | 'live' | 'fixtures' | 'manual') | null;
  /**
   * Есть ли статистика матча
   */
  hasStats?: boolean | null;
  /**
   * Приоритет матча (меньше = выше)
   */
  priority?: number | null;
  /**
   * Оригинальный объект матча из API
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📊 Детальная статистика матчей
 *
 * Просматривайте подробную статистику матчей: события, составы, дисциплину. Данные импортируются автоматически.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matchStats".
 */
export interface MatchStat {
  id: string;
  /**
   * ID матча из внешнего API
   */
  matchId: number;
  /**
   * Связь с матчем
   */
  match: string | Match;
  displayName?: string | null;
  /**
   * Владение мячом (%)
   */
  possession?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Удары
   */
  shots?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Удары в створ
   */
  shotsOnTarget?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Удары мимо створа
   */
  shotsOffTarget?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Заблокирован��ые удары
   */
  shotsBlocked?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Угловые
   */
  corners?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Офсайды
   */
  offsides?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Фолы
   */
  fouls?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Жёлтые карточки
   */
  yellowCards?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Красные карточки
   */
  redCards?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * ��ейвы вратарей
   */
  saves?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Передачи
   */
  passes?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Точные передачи
   */
  passesAccurate?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Точность передач (%)
   */
  passAccuracy?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Атаки
   */
  attacks?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Опасные атаки
   */
  dangerousAttacks?: {
    home?: number | null;
    away?: number | null;
  };
  /**
   * Оригинальный ответ API статистики
   */
  additionalStats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * События матча (голы, карточки, замены)
   */
  events?:
    | {
        minute: number;
        type: 'goal' | 'own_goal' | 'penalty' | 'yellow_card' | 'red_card' | 'substitution' | 'var' | 'other';
        team: 'home' | 'away';
        player?: string | null;
        assistPlayer?: string | null;
        playerOut?: string | null;
        playerIn?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Составы команд
   */
  lineups?: {
    home?: {
      formation?: string | null;
      startingXI?:
        | {
            number?: number | null;
            name: string;
            position?: string | null;
            id?: string | null;
          }[]
        | null;
      substitutes?:
        | {
            number?: number | null;
            name: string;
            position?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    away?: {
      formation?: string | null;
      startingXI?:
        | {
            number?: number | null;
            name: string;
            position?: string | null;
            id?: string | null;
          }[]
        | null;
      substitutes?:
        | {
            number?: number | null;
            name: string;
            position?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Время последней синхронизации
   */
  lastSyncAt?: string | null;
  /**
   * Источник данных
   */
  syncSource?: ('stats' | 'events' | 'lineups' | 'manual') | null;
  /**
   * Качество данных
   */
  dataQuality?: ('complete' | 'partial' | 'minimal' | 'none') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📈 Результаты и статистика прогнозов
 *
 * Просматривайте результаты прогнозов пользователей и начисленные очки. Данные создаются автоматически после завершения матча.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictionStats".
 */
export interface PredictionStat {
  id: string;
  displayName?: string | null;
  /**
   * Пост-прогноз, к которому относится статистика
   */
  post: string | Post;
  /**
   * Автор прогноза
   */
  author: string | User;
  /**
   * ID матча (из API)
   */
  matchId?: number | null;
  /**
   * ID фикстуры (из API)
   */
  fixtureId?: number | null;
  status: 'pending' | 'settled';
  /**
   * Время расчёта прогноза
   */
  evaluatedAt?: string | null;
  /**
   * Сводная статистика по событиям прогноза
   */
  summary?: {
    /**
     * Всего событий
     */
    total?: number | null;
    /**
     * Выиграло
     */
    won?: number | null;
    /**
     * Проиграло
     */
    lost?: number | null;
    /**
     * Не определено (нет данных/матч не окончен)
     */
    undecided?: number | null;
    /**
     * Процент попаданий (0..1)
     */
    hitRate?: number | null;
    /**
     * ROI по коэффициентам (если заданы), например 0.12 = +12%
     */
    roi?: number | null;
  };
  /**
   * Результаты по отдельным событиям
   */
  details?:
    | {
        /**
         * Строка события (например, "ТБ 2.5", "УГ ТМ 9.5")
         */
        event: string;
        /**
         * Коэффициент (если есть)
         */
        coefficient?: number | null;
        /**
         * Итог по событию
         */
        result: 'won' | 'lost' | 'undecided';
        /**
         * Причина, если результат не определён
         */
        reason?: ('unsupported_event' | 'match_not_finished' | 'no_score' | 'stat_unavailable' | 'unreachable') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Начисленные очки по прогнозу
   */
  scoring?: {
    /**
     * Сумма очков
     */
    points?: number | null;
    /**
     * Детализация расчёта (JSON)
     */
    breakdown?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 🎯 Рынки ставок для прогнозов
 *
 * Управляйте типами рынков ставок и связывайте их с группами исходов для структурирования прогнозов.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bet-markets".
 */
export interface BetMarket {
  id: string;
  /**
   * Название маркета (основные исходы, ЖК, КК, фолы, ауты и т.д.)
   */
  name: string;
  /**
   * Выберите группы исходов для этого маркета
   */
  groups?: (string | OutcomeGroup)[] | null;
  /**
   * Левая часть формулы: откуда берём число. Укажите источник статистики (statPath) и тип (statType).
   */
  mappingConfig?: {
    /**
     * Выберите поле статистики из MatchStats. Это левая часть формулы для проверки прогноза.
     */
    statPath?:
      | (
          | ''
          | 'possession'
          | 'shots'
          | 'shotsOnTarget'
          | 'shotsOffTarget'
          | 'shotsBlocked'
          | 'corners'
          | 'offsides'
          | 'fouls'
          | 'yellowCards'
          | 'redCards'
          | 'saves'
          | 'passes'
          | 'passesAccurate'
          | 'passAccuracy'
          | 'attacks'
          | 'dangerousAttacks'
          | 'outcome'
          | 'goals'
        )
      | null;
    /**
     * Тип статистики для этого маркета
     */
    statType?: ('none' | 'numeric' | 'outcome' | 'goals') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 🎲 Группы исходов для рынков ставок
 *
 * Создавайте группы возможных исходов и определяйте значения для каждого исхода.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outcome-groups".
 */
export interface OutcomeGroup {
  id: string;
  /**
   * Название группы исходов (тоталы, форы, обе забьют и т.д.)
   */
  name: string;
  /**
   * Правая часть формулы: как сравниваем метрику и с чем. Выберите оператор (comparisonOperator) и задайте значение/набор/диапазон/фильтр.
   */
  outcomes?:
    | {
        /**
         * Название исхода (например: "ТБ", "ТМ", "П1", "Х", "П2")
         */
        name: string;
        /**
         * Оператор сравнения. ТБ → Больше (>), ТМ → Меньше (<). Для диапазонов используйте "Диапазон (между)" и задайте границы ниже. Для двойного шанса и схожих — "Принадлежность множеству".
         */
        comparisonOperator?:
          | ('gt' | 'gte' | 'lt' | 'lte' | 'eq' | 'neq' | 'between' | 'in' | 'even' | 'odd' | 'exists')
          | null;
        /**
         * Область применения статистики. both = сумма home+away, home/away = значение команды, difference = home-away (для фор).
         */
        scope?: ('both' | 'home' | 'away' | 'difference') | null;
        /**
         * Способ вычисления фактического значения. Переопределяет поведение по умолчанию. Для «Обе забьют» выберите «Минимум». Для чёт/нечёт — «Чёт/Нечёт».
         */
        aggregation?: ('auto' | 'sum' | 'difference' | 'min' | 'max' | 'parity' | 'direct') | null;
        /**
         * Параметры для оператора "Диапазон (между)"
         */
        range?: {
          /**
           * Нижняя граница (включительно)
           */
          lower?: number | null;
          /**
           * Верхняя граница (включительно)
           */
          upper?: number | null;
        };
        /**
         * Для оператора "Принадлежность множеству". Пример: П1/Х → [1, 0].
         */
        set?:
          | {
              value: number;
              id?: string | null;
            }[]
          | null;
        /**
         * Параметры для оператора "Событие произошло": выберите тип события из MatchStats.events (например: red_card, penalty).
         */
        eventFilter?: {
          type: 'goal' | 'own_goal' | 'penalty' | 'yellow_card' | 'red_card' | 'var' | 'substitution';
          team?: ('any' | 'home' | 'away') | null;
          period?: ('any' | '1h' | '2h') | null;
        };
        /**
         * Значение исхода для сравнения (например, для "П1" = 1, для "Х" = 0, для "П2" = 2). Оставьте пустым, если используются динамические значения.
         */
        outcomeValue?: number | null;
        /**
         * Значения для этого исхода (например, 1.5, 2.0 для тоталов). Остав��те пустым для исходов без значений.
         */
        values?:
          | {
              /**
               * Числовое значение
               */
              value: number;
              id?: string | null;
            }[]
          | null;
        /**
         * Для комбинированных прогнозов (ОЗ + ТБ, ОЗ + ТМ и т.д.). Добавьте дополнительные условия, которые должны выполняться одновременно с основным.
         */
        conditions?:
          | {
              /**
               * Оператор сравнения для дополнительного условия
               */
              comparisonOperator: 'gt' | 'gte' | 'lt' | 'lte' | 'eq' | 'neq' | 'between' | 'in' | 'even' | 'odd';
              /**
               * Область применения статистики для этого условия
               */
              scope?: ('both' | 'home' | 'away' | 'difference') | null;
              /**
               * Способ вычисления для этого условия
               */
              aggregation: 'auto' | 'sum' | 'difference' | 'min' | 'max' | 'parity' | 'direct';
              /**
               * Значения для сравнения в этом условии
               */
              values?:
                | {
                    value: number;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Параметры для оператора "Диапазон (между)"
               */
              range?: {
                /**
                 * Нижняя граница (включительно)
                 */
                lower?: number | null;
                /**
                 * Верхняя граница (включительно)
                 */
                upper?: number | null;
              };
              /**
               * Для оператора "Принадлежность множеству"
               */
              set?:
                | {
                    value: number;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Логика объединения основного условия с дополнительными. AND = все условия истинны, OR = хотя бы одно истинно.
         */
        conditionLogic?: ('AND' | 'OR') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'commentVotes';
        value: string | CommentVote;
      } | null)
    | ({
        relationTo: 'leagues';
        value: string | League;
      } | null)
    | ({
        relationTo: 'matches';
        value: string | Match;
      } | null)
    | ({
        relationTo: 'matchStats';
        value: string | MatchStat;
      } | null)
    | ({
        relationTo: 'predictionStats';
        value: string | PredictionStat;
      } | null)
    | ({
        relationTo: 'bet-markets';
        value: string | BetMarket;
      } | null)
    | ({
        relationTo: 'outcome-groups';
        value: string | OutcomeGroup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  username?: T;
  name?: T;
  bio?: T;
  avatar?: T;
  avatarUrl?: T;
  links?:
    | T
    | {
        website?: T;
        twitter?: T;
        github?: T;
      };
  rating?: T;
  emailVerified?: T;
  emailVerificationToken?: T;
  emailVerificationExpires?: T;
  passwordResetToken?: T;
  passwordResetExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  postType?: T;
  content?: T;
  featuredImage?: T;
  matchId?: T;
  fixtureId?: T;
  prediction?:
    | T
    | {
        outcome?: T;
        score?:
          | T
          | {
              home?: T;
              away?: T;
            };
        fouls?:
          | T
          | {
              total?: T;
              overUnder?: T;
            };
        corners?:
          | T
          | {
              total?: T;
              home?: T;
              away?: T;
            };
        yellowCards?:
          | T
          | {
              total?: T;
              home?: T;
              away?: T;
            };
        events?:
          | T
          | {
              market?: T;
              scope?: T;
              stat?: T;
              outcome?: T;
              dc?: T;
              btts?: T;
              kind?: T;
              line?: T;
              team?: T;
              comboDc?: T;
              comboKind?: T;
              coefficient?: T;
              label?: T;
              id?: T;
            };
        matchInfo?:
          | T
          | {
              home?: T;
              away?: T;
              competition?: T;
              date?: T;
              time?: T;
            };
      };
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  parent?: T;
  content?: T;
  author?: T;
  upvotes?: T;
  downvotes?: T;
  score?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commentVotes_select".
 */
export interface CommentVotesSelect<T extends boolean = true> {
  comment?: T;
  user?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leagues_select".
 */
export interface LeaguesSelect<T extends boolean = true> {
  competitionId?: T;
  externalId?: T;
  name?: T;
  customName?: T;
  displayName?: T;
  countryId?: T;
  countryName?: T;
  isLeague?: T;
  isCup?: T;
  tier?: T;
  hasGroups?: T;
  active?: T;
  nationalTeamsOnly?: T;
  countries?:
    | T
    | {
        id?: T;
        name?: T;
      };
  federations?:
    | T
    | {
        id?: T;
        name?: T;
      };
  season?:
    | T
    | {
        id?: T;
        name?: T;
        start?: T;
        end?: T;
      };
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  matchId?: T;
  fixtureId?: T;
  externalId?: T;
  displayName?: T;
  date?: T;
  status?: T;
  minute?: T;
  period?: T;
  time?: T;
  scheduled?: T;
  addedAt?: T;
  lastChangedAt?: T;
  homeTeam?: T;
  homeTeamId?: T;
  homeLogo?: T;
  homeCountryId?: T;
  homeStadium?: T;
  awayTeam?: T;
  awayTeamId?: T;
  awayLogo?: T;
  awayCountryId?: T;
  awayStadium?: T;
  homeScore?: T;
  awayScore?: T;
  homeScoreHalftime?: T;
  awayScoreHalftime?: T;
  homeScoreExtraTime?: T;
  awayScoreExtraTime?: T;
  homeScorePenalties?: T;
  awayScorePenalties?: T;
  scoresRaw?:
    | T
    | {
        score?: T;
        htScore?: T;
        ftScore?: T;
        etScore?: T;
        psScore?: T;
      };
  competition?: T;
  competitionId?: T;
  competitionDetails?:
    | T
    | {
        isCup?: T;
        isLeague?: T;
        hasGroups?: T;
        nationalTeamsOnly?: T;
        active?: T;
        tier?: T;
      };
  federation?:
    | T
    | {
        federationId?: T;
        name?: T;
      };
  country?:
    | T
    | {
        countryId?: T;
        name?: T;
        flag?: T;
        fifaCode?: T;
        uefaCode?: T;
        isReal?: T;
      };
  groupId?: T;
  league?: T;
  season?:
    | T
    | {
        seasonId?: T;
        name?: T;
        year?: T;
      };
  round?: T;
  location?: T;
  venue?:
    | T
    | {
        name?: T;
        city?: T;
        country?: T;
      };
  referee?: T;
  outcomes?:
    | T
    | {
        halfTime?: T;
        fullTime?: T;
        extraTime?: T;
        penaltyShootout?: T;
      };
  odds?:
    | T
    | {
        pre?:
          | T
          | {
              home?: T;
              draw?: T;
              away?: T;
            };
        live?:
          | T
          | {
              home?: T;
              draw?: T;
              away?: T;
            };
      };
  urls?:
    | T
    | {
        events?: T;
        statistics?: T;
        lineups?: T;
        head2head?: T;
      };
  lastSyncAt?: T;
  syncSource?: T;
  hasStats?: T;
  priority?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matchStats_select".
 */
export interface MatchStatsSelect<T extends boolean = true> {
  matchId?: T;
  match?: T;
  displayName?: T;
  possession?:
    | T
    | {
        home?: T;
        away?: T;
      };
  shots?:
    | T
    | {
        home?: T;
        away?: T;
      };
  shotsOnTarget?:
    | T
    | {
        home?: T;
        away?: T;
      };
  shotsOffTarget?:
    | T
    | {
        home?: T;
        away?: T;
      };
  shotsBlocked?:
    | T
    | {
        home?: T;
        away?: T;
      };
  corners?:
    | T
    | {
        home?: T;
        away?: T;
      };
  offsides?:
    | T
    | {
        home?: T;
        away?: T;
      };
  fouls?:
    | T
    | {
        home?: T;
        away?: T;
      };
  yellowCards?:
    | T
    | {
        home?: T;
        away?: T;
      };
  redCards?:
    | T
    | {
        home?: T;
        away?: T;
      };
  saves?:
    | T
    | {
        home?: T;
        away?: T;
      };
  passes?:
    | T
    | {
        home?: T;
        away?: T;
      };
  passesAccurate?:
    | T
    | {
        home?: T;
        away?: T;
      };
  passAccuracy?:
    | T
    | {
        home?: T;
        away?: T;
      };
  attacks?:
    | T
    | {
        home?: T;
        away?: T;
      };
  dangerousAttacks?:
    | T
    | {
        home?: T;
        away?: T;
      };
  additionalStats?: T;
  events?:
    | T
    | {
        minute?: T;
        type?: T;
        team?: T;
        player?: T;
        assistPlayer?: T;
        playerOut?: T;
        playerIn?: T;
        description?: T;
        id?: T;
      };
  lineups?:
    | T
    | {
        home?:
          | T
          | {
              formation?: T;
              startingXI?:
                | T
                | {
                    number?: T;
                    name?: T;
                    position?: T;
                    id?: T;
                  };
              substitutes?:
                | T
                | {
                    number?: T;
                    name?: T;
                    position?: T;
                    id?: T;
                  };
            };
        away?:
          | T
          | {
              formation?: T;
              startingXI?:
                | T
                | {
                    number?: T;
                    name?: T;
                    position?: T;
                    id?: T;
                  };
              substitutes?:
                | T
                | {
                    number?: T;
                    name?: T;
                    position?: T;
                    id?: T;
                  };
            };
      };
  lastSyncAt?: T;
  syncSource?: T;
  dataQuality?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictionStats_select".
 */
export interface PredictionStatsSelect<T extends boolean = true> {
  displayName?: T;
  post?: T;
  author?: T;
  matchId?: T;
  fixtureId?: T;
  status?: T;
  evaluatedAt?: T;
  summary?:
    | T
    | {
        total?: T;
        won?: T;
        lost?: T;
        undecided?: T;
        hitRate?: T;
        roi?: T;
      };
  details?:
    | T
    | {
        event?: T;
        coefficient?: T;
        result?: T;
        reason?: T;
        id?: T;
      };
  scoring?:
    | T
    | {
        points?: T;
        breakdown?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bet-markets_select".
 */
export interface BetMarketsSelect<T extends boolean = true> {
  name?: T;
  groups?: T;
  mappingConfig?:
    | T
    | {
        statPath?: T;
        statType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outcome-groups_select".
 */
export interface OutcomeGroupsSelect<T extends boolean = true> {
  name?: T;
  outcomes?:
    | T
    | {
        name?: T;
        comparisonOperator?: T;
        scope?: T;
        aggregation?: T;
        range?:
          | T
          | {
              lower?: T;
              upper?: T;
            };
        set?:
          | T
          | {
              value?: T;
              id?: T;
            };
        eventFilter?:
          | T
          | {
              type?: T;
              team?: T;
              period?: T;
            };
        outcomeValue?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        conditions?:
          | T
          | {
              comparisonOperator?: T;
              scope?: T;
              aggregation?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              range?:
                | T
                | {
                    lower?: T;
                    upper?: T;
                  };
              set?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        conditionLogic?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * ⚽ **Виджет топ-матчей на главной странице**
 *
 * **Что здесь делать:**
 * • Настраивать список лиг для отображения на главной странице
 * • Управлять приоритетами лиг (какие показывать первыми)
 * • Настраивать фильтры и временные диапазоны
 *
 * **Как настроить:**
 * 1. Включите виджет (галочка "Включить виджет топ матчей")
 * 2. Укажите заголовок виджета
 * 3. Установите максимальное количество матчей
 * 4. Добавьте лиги через "Add Leagues"
 * 5. Для каждой лиги установите приоритет (меньше число = выше в списке)
 * 6. Настройте фильтры (временной диапазон, только активные и т.д.)
 *
 * **Приоритеты:**
 * • 1-10: Топовые лиги (АПЛ, Ла Лига, Бундеслига)
 * • 11-50: Второстепенные лиги
 * • 51+: Остальные лиги
 *
 * ⚠️ Доступно только администраторам
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topMatchesLeagues".
 */
export interface TopMatchesLeague {
  id: string;
  /**
   * Показывать ли виджет топ матчей на сайте
   */
  enabled?: boolean | null;
  /**
   * Заголовок, который будет отображаться над виджетом
   */
  title?: string | null;
  /**
   * Максимальное количество матчей для показа в виджете
   */
  maxMatches?: number | null;
  /**
   * Выберите лиги для отображения в виджете топ матчей
   */
  leagues?:
    | {
        /**
         * Выберите лигу
         */
        league: string | League;
        /**
         * Приоритет лиги (меньше число = выше приоритет)
         */
        priority?: number | null;
        /**
         * Показывать ли матчи из этой лиги
         */
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Дополнительные настройки для фильтрации матчей
   */
  filterSettings?: {
    /**
     * Показывать матчи только из активных лиг
     */
    showOnlyActive?: boolean | null;
    /**
     * В каком временном диапазоне искать матчи
     */
    timeRange?: ('today' | 'tomorrow' | 'week' | 'month') | null;
    /**
     * Не показывать завершённые матчи
     */
    excludeFinished?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 📋 **Настройка лиг в боковом меню**
 *
 * **Что здесь делать:**
 * • Настраивать список лиг для отображения в левом сайдбаре
 * • Управлять порядком и внешним видом лиг
 * • Настраивать группировку и дополнительные опции
 *
 * **Как настроить:**
 * 1. Включите отображение (галочка "Показывать лиги в сайдбаре")
 * 2. Укажите заголовок секции
 * 3. Установите максимальное количество лиг
 * 4. Добавьте лиги через "Add Leagues"
 * 5. Для каждой лиги:
 *    - Установите порядок сортировки (меньше = выше)
 *    - Можно задать кастомное название
 *    - Выбрать цвет выделения
 *    - Включить счётчик матчей
 *
 * **Настройки отображения:**
 * • Показывать флаги стран
 * • Группировать по странам
 * • Компактный режим
 * • Показывать логотипы лиг
 *
 * ⚠️ Доступно только администраторам
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebarLeagues".
 */
export interface SidebarLeague {
  id: string;
  /**
   * Включить/выключить отображение списка лиг в сайдбаре
   */
  enabled?: boolean | null;
  /**
   * Заголовок секции с лигами в сайдбаре
   */
  title?: string | null;
  /**
   * Максимальное количество лиг для показа в сайдбаре
   */
  maxItems?: number | null;
  /**
   * Отображать флаги стран рядом с названиями лиг
   */
  showFlags?: boolean | null;
  /**
   * Группировать лиги по странам в сайдбаре
   */
  groupByCountry?: boolean | null;
  /**
   * Выберите лиги для отображения в сайдбаре
   */
  leagues?:
    | {
        /**
         * Выберите лигу
         */
        league: string | League;
        /**
         * Оставьте пустым для использования оригинального названия лиги
         */
        customName?: string | null;
        /**
         * Порядок отображения в сайдбаре (меньше число = выше в списке)
         */
        priority?: number | null;
        /**
         * Показывать ли эту лигу в сайдбаре
         */
        enabled?: boolean | null;
        /**
         * HEX-код цвета для выделения лиги (например, #ff0000)
         */
        highlightColor?: string | null;
        /**
         * Отображать количество предстоящих матчей рядом с названием лиги
         */
        showMatchCount?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Дополнительные настройки внешнего вида сайдбара
   */
  displaySettings?: {
    /**
     * Показывать только активные лиги
     */
    showOnlyActive?: boolean | null;
    /**
     * Отображать уровень лиги (1-я лига, 2-я лига �� т.д.)
     */
    showTiers?: boolean | null;
    /**
     * Более компактное отображение списка лиг
     */
    compactMode?: boolean | null;
    /**
     * Отображать логотипы лиг (если доступны)
     */
    showLogos?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * ⚙️ **Центр управления исходами ставок**
 *
 * **Что здесь делать:**
 * • Централизованное управление системой исходов
 * • Настройка глобальных параметров
 * • Документация по работе с исходами
 *
 * **Связанные разделы:**
 * • **Рынки ставок** (Markets) - типы рынков
 * • **Группы исходов** (Outcome Groups) - варианты исходов
 *
 * **Как работает система:**
 * 1. Создаёте группу исходов (например, "Тоталы голов")
 * 2. Добавляете исходы с значениями (ТБ: 0.5, 1.5, 2.5...)
 * 3. Создаёте рынок (например, "Голы")
 * 4. Связываете рынок с группами исходов
 * 5. Рынок становится доступен в прогнозах
 *
 * **Примеры настройки:**
 * • Основные исходы: П1/Х/П2 (без линий)
 * • Тоталы: ТБ/ТМ с линиями 0.5, 1.5, 2.5...
 * • Угловые: ТБ/ТМ с линиями 8.5, 9.5, 10.5...
 *
 * ⚠️ Доступно только администраторам
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outcome-manager".
 */
export interface OutcomeManager {
  id: string;
  /**
   * Описание управления исходами.
   */
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 🔗 **Настройка меню в шапке сайта**
 *
 * **Что здесь делать:**
 * • Добавлять и редактировать пункты главного меню
 * • Настраивать навигацию по сайту
 * • Управлять порядком отображения пунктов
 *
 * **Как использовать:**
 * 1. Нажмите "Add Item" для добавления нового пункта
 * 2. Укажите текст пункта меню
 * 3. Введите URL (внутренний: /leagues или внешний: https://example.com)
 * 4. Сохраните изменения
 *
 * **Примеры URL:**
 * • Внутренние страницы: /leagues, /matches, /predictions
 * • Внешние ссылки: https://example.com
 *
 * ⚠️ Доступно только администраторам
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-menu".
 */
export interface HeaderMenu {
  id: string;
  items?:
    | {
        label: string;
        /**
         * Абсолютный или относительный URL (например, /leagues или https://example.com)
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topMatchesLeagues_select".
 */
export interface TopMatchesLeaguesSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  maxMatches?: T;
  leagues?:
    | T
    | {
        league?: T;
        priority?: T;
        enabled?: T;
        id?: T;
      };
  filterSettings?:
    | T
    | {
        showOnlyActive?: T;
        timeRange?: T;
        excludeFinished?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebarLeagues_select".
 */
export interface SidebarLeaguesSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  maxItems?: T;
  showFlags?: T;
  groupByCountry?: T;
  leagues?:
    | T
    | {
        league?: T;
        customName?: T;
        priority?: T;
        enabled?: T;
        highlightColor?: T;
        showMatchCount?: T;
        id?: T;
      };
  displaySettings?:
    | T
    | {
        showOnlyActive?: T;
        showTiers?: T;
        compactMode?: T;
        showLogos?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outcome-manager_select".
 */
export interface OutcomeManagerSelect<T extends boolean = true> {
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-menu_select".
 */
export interface HeaderMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}