/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getCompetitionsListJson } from './getCompetitionsListJson.ts'
import { getCountriesListJson } from './getCountriesListJson.ts'
import { getFederationsListJson } from './getFederationsListJson.ts'
import { getSeasonsListJson } from './getSeasonsListJson.ts'
import { getTeamsListJson } from './getTeamsListJson.ts'

export function catalogsService() {
  return {
    getCompetitionsListJson,
    getCountriesListJson,
    getFederationsListJson,
    getTeamsListJson,
    getSeasonsListJson,
  }
}
