/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetCompetitionsListJsonQueryResponse, GetCompetitionsListJsonQueryParams, GetCompetitionsListJson400, GetCompetitionsListJson401, GetCompetitionsListJson404, GetCompetitionsListJson500 } from "../../types/GetCompetitionsListJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetCompetitionsListJsonUrl() {
  const res = { method: 'GET', url: `/competitions/list.json` as const }  
  return res
}

/**
 * @description Возвращает список всех соревнований (лиг, кубков), поддерживаемых API, с их основными данными. Можно фильтровать список по стране или федерации.  **Параметры фильтрации:**  - `country_id`: если указан, возвращаются соревнования только этой страны (при одновременном указании federation_id и country_id – приоритет у country_id).  - `federation_id`: если указан, возвращаются соревнования, относящиеся к данной международной федерации (например, все турниры под эгидой UEFA).  - Поддерживаются параметры пагинации `page` и `size`. По умолчанию может возвращаться первая страница результатов.  **Пример запроса (соревнования по стране с ID=1):**  `GET /competitions/list.json?country_id=1&key=YOUR_KEY&secret=YOUR_SECRET`
 * @summary Список соревнований (лиг и кубков)
 * {@link /competitions/list.json}
 */
export async function getCompetitionsListJson(params?: GetCompetitionsListJsonQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCompetitionsListJsonQueryResponse, ResponseErrorConfig<GetCompetitionsListJson400 | GetCompetitionsListJson401 | GetCompetitionsListJson404 | GetCompetitionsListJson500>, unknown>({ method : "GET", url : getGetCompetitionsListJsonUrl().url.toString(), params, ... requestConfig })  
  return res
}