/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetCompetitionsListJsonQueryResponse,
  GetCompetitionsListJsonQueryParams,
  GetCompetitionsListJson400,
  GetCompetitionsListJson401,
  GetCompetitionsListJson404,
  GetCompetitionsListJson500,
} from '../../types/GetCompetitionsListJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetCompetitionsListJsonUrl() {
  const res = { method: 'GET', url: `/competitions/list.json` as const }
  return res
}

/**
 * @summary Список соревнований
 * {@link /competitions/list.json}
 */
export async function getCompetitionsListJson(
  params?: GetCompetitionsListJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetCompetitionsListJsonQueryResponse,
    ResponseErrorConfig<
      | GetCompetitionsListJson400
      | GetCompetitionsListJson401
      | GetCompetitionsListJson404
      | GetCompetitionsListJson500
    >,
    unknown
  >({
    method: 'GET',
    url: getGetCompetitionsListJsonUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res
}
