/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetCountriesListJsonQueryResponse,
  GetCountriesListJsonQueryParams,
  GetCountriesListJson400,
  GetCountriesListJson401,
  GetCountriesListJson404,
  GetCountriesListJson500,
} from '../../types/GetCountriesListJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetCountriesListJsonUrl() {
  const res = { method: 'GET', url: `/countries/list.json` as const }
  return res
}

/**
 * @summary Список стран
 * {@link /countries/list.json}
 */
export async function getCountriesListJson(
  params?: GetCountriesListJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetCountriesListJsonQueryResponse,
    ResponseErrorConfig<
      | GetCountriesListJson400
      | GetCountriesListJson401
      | GetCountriesListJson404
      | GetCountriesListJson500
    >,
    unknown
  >({ method: 'GET', url: getGetCountriesListJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
