/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetFederationsListJsonQueryResponse, GetFederationsListJson400, GetFederationsListJson401, GetFederationsListJson404, GetFederationsListJson500 } from "../../types/GetFederationsListJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetFederationsListJsonUrl() {
  const res = { method: 'GET', url: `/federations/list.json` as const }  
  return res
}

/**
 * @description Возвращает список всех футбольных федераций (конфедераций), информация о которых используется в API. Примеры федераций: FIFA (ид=1), UEFA (2), CONMEBOL (6) и т.д.  В общем случае фильтры не требуются (список небольшой и содержит основные конфедерации). Данные по федерациям могут использоваться для фильтрации стран и соревнований.
 * @summary Список федераций
 * {@link /federations/list.json}
 */
export async function getFederationsListJson(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetFederationsListJsonQueryResponse, ResponseErrorConfig<GetFederationsListJson400 | GetFederationsListJson401 | GetFederationsListJson404 | GetFederationsListJson500>, unknown>({ method : "GET", url : getGetFederationsListJsonUrl().url.toString(), ... requestConfig })  
  return res
}