/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetFederationsListJsonQueryResponse,
  GetFederationsListJson400,
  GetFederationsListJson401,
  GetFederationsListJson404,
  GetFederationsListJson500,
} from '../../types/GetFederationsListJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetFederationsListJsonUrl() {
  const res = { method: 'GET', url: `/federations/list.json` as const }
  return res
}

/**
 * @summary Список федераций
 * {@link /federations/list.json}
 */
export async function getFederationsListJson(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetFederationsListJsonQueryResponse,
    ResponseErrorConfig<
      | GetFederationsListJson400
      | GetFederationsListJson401
      | GetFederationsListJson404
      | GetFederationsListJson500
    >,
    unknown
  >({ method: 'GET', url: getGetFederationsListJsonUrl().url.toString(), ...requestConfig })
  return res
}
