/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetSeasonsListJsonQueryResponse, GetSeasonsListJson400, GetSeasonsListJson401, GetSeasonsListJson404, GetSeasonsListJson500 } from "../../types/GetSeasonsListJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetSeasonsListJsonUrl() {
  const res = { method: 'GET', url: `/seasons/list.json` as const }  
  return res
}

/**
 * @description Возвращает список сезонов, известных системе (например, 2020, 2021/2022 и т.п.), с указанием их идентификаторов. Эти идентификаторы сезонов используются в других методах (например, для запроса турнирной таблицы конкретного сезона или статистики). В большинстве случаев этот эндпоинт используется для справки, так как актуальные сезоны возвращаются в данных соревнований.
 * @summary Список сезонов
 * {@link /seasons/list.json}
 */
export async function getSeasonsListJson(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetSeasonsListJsonQueryResponse, ResponseErrorConfig<GetSeasonsListJson400 | GetSeasonsListJson401 | GetSeasonsListJson404 | GetSeasonsListJson500>, unknown>({ method : "GET", url : getGetSeasonsListJsonUrl().url.toString(), ... requestConfig })  
  return res
}