/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/http/livescore/customFetch";
import type { GetSeasonsListJsonQueryResponse, GetSeasonsListJson400, GetSeasonsListJson401, GetSeasonsListJson404, GetSeasonsListJson500 } from "../../types/GetSeasonsListJson.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/http/livescore/customFetch";

export function getGetSeasonsListJsonUrl() {
  const res = { method: 'GET', url: `/seasons/list.json` as const }  
  return res
}

/**
 * @summary Список сезонов
 * {@link /seasons/list.json}
 */
export async function getSeasonsListJson(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetSeasonsListJsonQueryResponse, ResponseErrorConfig<GetSeasonsListJson400 | GetSeasonsListJson401 | GetSeasonsListJson404 | GetSeasonsListJson500>, unknown>({ method : "GET", url : getGetSeasonsListJsonUrl().url.toString(), ... requestConfig })  
  return res
}