/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTeamsLastmatchesJsonQueryResponse,
  GetTeamsLastmatchesJsonQueryParams,
  GetTeamsLastmatchesJson400,
  GetTeamsLastmatchesJson401,
  GetTeamsLastmatchesJson404,
  GetTeamsLastmatchesJson500,
} from '../../types/GetTeamsLastmatchesJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTeamsLastmatchesJsonUrl() {
  const res = { method: 'GET', url: `/teams/lastmatches.json` as const }
  return res
}

/**
 * @summary Последние матчи команды
 * {@link /teams/lastmatches.json}
 */
export async function getTeamsLastmatchesJson(
  params: GetTeamsLastmatchesJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTeamsLastmatchesJsonQueryResponse,
    ResponseErrorConfig<
      | GetTeamsLastmatchesJson400
      | GetTeamsLastmatchesJson401
      | GetTeamsLastmatchesJson404
      | GetTeamsLastmatchesJson500
    >,
    unknown
  >({
    method: 'GET',
    url: getGetTeamsLastmatchesJsonUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res
}
