/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/http/livescore/customFetch'
import type {
  GetTeamsListJsonQueryResponse,
  GetTeamsListJsonQueryParams,
  GetTeamsListJson400,
  GetTeamsListJson401,
  GetTeamsListJson404,
  GetTeamsListJson500,
} from '../../types/GetTeamsListJson.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/http/livescore/customFetch'

export function getGetTeamsListJsonUrl() {
  const res = { method: 'GET', url: `/teams/list.json` as const }
  return res
}

/**
 * @summary Список команд
 * {@link /teams/list.json}
 */
export async function getTeamsListJson(
  params?: GetTeamsListJsonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetTeamsListJsonQueryResponse,
    ResponseErrorConfig<
      GetTeamsListJson400 | GetTeamsListJson401 | GetTeamsListJson404 | GetTeamsListJson500
    >,
    unknown
  >({ method: 'GET', url: getGetTeamsListJsonUrl().url.toString(), params, ...requestConfig })
  return res
}
